"""SOLIDWORKS API libraries besides sldworks: metadata for swpy._interop.

Auto-generated by tools/gen_interop.py - do not edit.
"""
LIBRARIES = {
    'cosworks': {'title': 'SOLIDWORKS Simulation', 'namespace': 'SolidWorks.Interop.cosworks', 'assembly': 'SolidWorks.Interop.cosworks', 'file': 'api\\redist\\SolidWorks.Interop.cosworks.dll', 'casts': 'Cast_cosworks', 'interfaces': 160, 'enums': 347},
    'swmotionstudy': {'title': 'Motion studies', 'namespace': 'SolidWorks.Interop.swmotionstudy', 'assembly': 'SolidWorks.Interop.swmotionstudy', 'file': 'api\\redist\\SolidWorks.Interop.swmotionstudy.dll', 'casts': 'Cast_swmotionstudy', 'interfaces': 18, 'enums': 5},
    'swdimxpert': {'title': 'DimXpert', 'namespace': 'SolidWorks.Interop.swdimxpert', 'assembly': 'SolidWorks.Interop.swdimxpert', 'file': 'api\\redist\\SolidWorks.Interop.swdimxpert.dll', 'casts': 'Cast_swdimxpert', 'interfaces': 98, 'enums': 23},
    'SWRoutingLib': {'title': 'Routing', 'namespace': 'SolidWorks.Interop.SWRoutingLib', 'assembly': 'SolidWorks.Interop.SWRoutingLib', 'file': 'SolidWorks.Interop.SWRoutingLib.dll', 'casts': 'Cast_SWRoutingLib', 'interfaces': 28, 'enums': 26},
    'sldcostingapi': {'title': 'Costing', 'namespace': 'SolidWorks.Interop.sldcostingapi', 'assembly': 'SolidWorks.Interop.sldcostingapi', 'file': 'api\\redist\\SolidWorks.Interop.sldcostingapi.dll', 'casts': 'Cast_sldcostingapi', 'interfaces': 28, 'enums': 24},
    'dsgnchk': {'title': 'Design Checker', 'namespace': 'SolidWorks.Interop.dsgnchk', 'assembly': 'SolidWorks.Interop.dsgnchk', 'file': 'api\\redist\\SolidWorks.Interop.dsgnchk.dll', 'casts': 'Cast_dsgnchk', 'interfaces': 10, 'enums': 1},
    'fworks': {'title': 'FeatureWorks', 'namespace': 'SolidWorks.Interop.fworks', 'assembly': 'SolidWorks.Interop.fworks', 'file': 'api\\redist\\SolidWorks.Interop.fworks.dll', 'casts': 'Cast_fworks', 'interfaces': 2, 'enums': 5},
    'gtswutilities': {'title': 'Utilities', 'namespace': 'SolidWorks.Interop.gtswutilities', 'assembly': 'SolidWorks.Interop.gtswutilities', 'file': 'api\\redist\\SolidWorks.Interop.gtswutilities.dll', 'casts': 'Cast_gtswutilities', 'interfaces': 22, 'enums': 13},
    'sldtoolboxconfigureaddin': {'title': 'Toolbox', 'namespace': 'SolidWorks.Interop.sldtoolboxconfigureaddin', 'assembly': 'SolidWorks.Interop.sldtoolboxconfigureaddin', 'file': 'api\\redist\\SolidWorks.Interop.sldtoolboxconfigureaddin.dll', 'casts': 'Cast_sldtoolboxconfigureaddin', 'interfaces': 4, 'enums': 0},
    'sustainability': {'title': 'Sustainability', 'namespace': 'SolidWorks.Interop.sustainability', 'assembly': 'SolidWorks.Interop.sustainability', 'file': 'api\\redist\\SolidWorks.Interop.sustainability.dll', 'casts': 'Cast_sustainability', 'interfaces': 18, 'enums': 8},
    'sw3dprinter': {'title': '3D printing', 'namespace': 'SolidWorks.Interop.sw3dprinter', 'assembly': 'SolidWorks.Interop.sw3dprinter', 'file': 'api\\redist\\SolidWorks.Interop.sw3dprinter.dll', 'casts': 'Cast_sw3dprinter', 'interfaces': 2, 'enums': 11},
    'swbrowser': {'title': 'Design Library browser', 'namespace': 'SolidWorks.Interop.swbrowser', 'assembly': 'SolidWorks.Interop.swbrowser', 'file': 'api\\redist\\SolidWorks.Interop.swbrowser.dll', 'casts': 'Cast_swbrowser', 'interfaces': 4, 'enums': 3},
    'swcommands': {'title': 'Command IDs for ISldWorks.RunCommand', 'namespace': 'SolidWorks.Interop.swcommands', 'assembly': 'SolidWorks.Interop.swcommands', 'file': 'api\\redist\\SolidWorks.Interop.swcommands.dll', 'casts': 'Cast_swcommands', 'interfaces': 0, 'enums': 2},
    'swdocumentmgr': {'title': 'Document Manager (needs a licence key)', 'namespace': 'SolidWorks.Interop.swdocumentmgr', 'assembly': 'SolidWorks.Interop.swdocumentmgr', 'file': 'api\\redist\\SolidWorks.Interop.swdocumentmgr.dll', 'casts': 'Cast_swdocumentmgr', 'interfaces': 270, 'enums': 59},
    'EdmLib': {'title': 'SOLIDWORKS PDM Professional', 'namespace': 'EdmLib', 'assembly': 'Interop.SWEdmLib', 'file': 'Interop.SWEdmLib.dll', 'casts': 'Cast_EdmLib', 'interfaces': 212, 'enums': 110},
    'pdmworks': {'title': 'Workgroup PDM (legacy)', 'namespace': 'PDMWorks.Interop.pdmworks', 'assembly': 'PDMWorks.Interop.pdmworks', 'file': 'api\\redist\\PDMWorks.Interop.pdmworks.dll', 'casts': 'Cast_pdmworks', 'interfaces': 44, 'enums': 7},
}
