"""Design Checker API constants (SolidWorks.Interop.dsgnchk 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class dsgnchkError_e(_Enum):
    dsgnchkNOErr = 0
    dsgnchkReportAlreadyExists = 1
    dsgnchkCouldNotCreateReportDirectory = 2
    dsgnchkNoActivedocument = 3
    dsgnchkStandardFileDoesNotExist = 4
    dsgnchkInvalidReportName = 5
    dsgnchkAllStandardFilesInvalid = 6
    dsgnchkDesignCheckerAlreadyRunning = 7
    dsgnchkInvalidCallToAPI = 8
    dsgnchkUnknownErr = -1
