"""SOLIDWORKS PDM Professional API constants (Interop.SWEdmLib 5.21.0.0).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class CreateMenuFlags(_Enum):
    Cmf_AllItemsInSameFolder = 1
    Cmf_IncludeAdminReactors = 2
    Cmf_GrayOutInvalidItems = 4
    Cmf_ContextMenu = 8
    Cmf_DisableAddInReload = 16
    Cmf_AddMenuIcons = 32
    Cmf_ContextMenuItem = 64
    Cmf_ContextMenuItemFolder = 128
    Cmf_ItemToolsMenu = 256
    Cmf_MenuBarAction = 512
    Cmf_MenuBarModify = 1024
    Cmf_MenuBarDisplay = 2048
    Cmf_MenuBarTools = 4096

class EdmAddAddInFlags(_Enum):
    EdmAddin_Nothing = 0
    EdmAddin_AddAllFilesToOneAddIn = 1
    EdmAddin_ReplaceDuplicates = 2

class EdmAddCallbackMsgID(_Enum):
    EdmAddMsg_GenericError = 0
    EdmAddMsg_ReplaceLocal = 1
    EdmAddMsg_ClearUnique = 2
    EdmAddMsg_MissingPluginComponent = 3
    EdmAddMsg_FileFmtReadError = 4
    EdmAddMsg_DeleteSource = 5

class EdmAddFileDlgFlag(_Enum):
    Eafdf_Nothing = 0

class EdmAddFlag(_Enum):
    EdmAdd_Simple = 0
    EdmAdd_Refresh = 1
    EdmAdd_DontAddCorrupt = 2
    EdmAdd_KeepExistingSerialNumbers = 4
    EdmAdd_UniqueVarClearDuplicate = 16
    EdmAdd_UniqueVarDelayCheck = 32
    EdmAdd_DeleteSource = 64
    EdmAdd_ForceGenerateSerialNumbers = 128
    EdmAdd_GetInterface = 256

class EdmAddInFileInfoFlags(_Enum):
    EdmAdfif_DataFile = 0
    EdmAdfif_ComDll32 = 1
    EdmAdfif_AddInObject32 = 2
    EdmAdfif_ComDll64 = 4
    EdmAdfif_AddInObject64 = 8

class EdmBatchAddFlag(_Enum):
    EdmBaf_Nothing = 0
    EdmBaf_ReplaceDuplicateFiles = 1

class EdmBatchAddFolderFlag(_Enum):
    Ebaff_Nothing = 0
    Ebaff_GetInterface = 1
    Ebaff_DisableRefresh = 2

class EdmBatchCreateFolderFlag(_Enum):
    Ebcf_Nothing = 0
    Ebcf_RenameExistingRoots = 1

class EdmBatchFlags(_Enum):
    EdmBatch_Nothing = 0
    EdmBatch_AllConfigs = 1
    EdmBatch_RefreshPreview = 2

class EdmBomColumnType(_Enum):
    EdmBomCol_Variable = 0
    EdmBomCol_Name = 1
    EdmBomCol_FileSize = 2
    EdmBomCol_Date = 3
    EdmBomCol_LatestVersion = 4
    EdmBomCol_Path = 5
    EdmBomCol_State = 6
    EdmBomCol_LockUser = 7
    EdmBomCol_LockedIn = 8
    EdmBomCol_FoundInVersion = 9
    EdmBomCol_FileType = 10
    EdmBomCol_RefCount = 11
    EdmBomCol_DocType = 12
    EdmBomCol_LockUserID = 13
    EdmBomCol_LockPath = 14
    EdmBomCol_LockDomain = 15
    EdmBomCol_StateName = 16
    EdmBomCol_LatestFileDate = 17
    EdmBomCol_LockViewID = 18
    EdmBomCol_Shared = 19
    EdmBomCol_Configuration = 21
    EdmBomCol_RefVariable = 22
    EdmBomCol_ID = 23
    EdmBomCol_PartNumber = 24
    EdmBomCol_RefCountNoBomQty = 25

class EdmBomFlag(_Enum):
    EdmBf_AsBuilt = 1
    EdmBf_ShowSelected = 2

class EdmBomInsertRowOption(_Enum):
    EdmBomInsertRowOption_AboveRow = 0
    EdmBomInsertRowOption_BelowRow = 1
    EdmBomInsertRowOption_AsChild = 2

class EdmBomSetVarOption(_Enum):
    EdmBomSetVarOption_Computed = 0
    EdmBomSetVarOption_Edited = 1
    EdmBomSetVarOption_Both = 2

class EdmBomVersionType(_Enum):
    EdmBomVer_Version = 0
    EdmBomVer_Revision = 1
    EdmBomVer_Label = 2

class EdmBrowseFlag(_Enum):
    EdmBws_ForOpen = 0
    EdmBws_ForSave = 1
    EdmBws_PermitMultipleSel = 2
    EdmBws_PermitLocalFiles = 4
    EdmBws_PermitVaultFiles = 8
    EdmBws_PermitExternalFiles = 16
    EdmBws_Help = 32

class EdmBrowseForFolderFlag(_Enum):
    EdmBwsFld_None = 0
    EdmBwsFld_ExclFileFolders = 1
    EdmBwsFld_ExclItemFolders = 2

class EdmButtonState(_Enum):
    BState_Hot = 1
    BState_Cold = 2
    BState_Disabled = 3

class EdmCardControlType(_Enum):
    EdmCtrl_Invalid = 0
    EdmCtrl_Image = 1
    EdmCtrl_Text = 2
    EdmCtrl_Frame = 3
    EdmCtrl_Editbox = 4
    EdmCtrl_Button = 5
    EdmCtrl_RadioColumn = 6
    EdmCtrl_ComboboxSimple = 7
    EdmCtrl_ComboboxDropdown = 8
    EdmCtrl_ComboboxDroplist = 9
    EdmCtrl_Listbox = 10
    EdmCtrl_Tab = 11
    EdmCtrl_Viewer = 12
    EdmCtrl_Checkbox = 13
    EdmCtrl_DatePicker = 14
    EdmCtrl_CustomPropertySearch = 15
    EdmCtrl_CustomVariableTree = 16

class EdmCardFlag(_Enum):
    EdmCF_Nothing = 0
    EdmCF_CloseDlgOK = 1
    EdmCF_CloseDlgCancel = 2

class EdmCardType(_Enum):
    EdmCard_File = 0
    EdmCard_Folder = 1
    EdmCard_Template = 2
    EdmCard_Search = 3

class EdmCardViewCallbackMaskBits(_Enum):
    Edmcvcm_CallSetModifiedFlag = 1
    Edmcvcm_CallOnAddInInput = 2
    Edmcvcm_CallGetCtrlData = 4
    Edmcvcm_CallGetDefaultValueComponent = 8
    Edmcvcm_CallCreateCustomCtrl = 16
    Edmcmcm_CallSetCtrlData = 32

class EdmCardViewFlag(_Enum):
    EdmCvf_Nothing = 0
    EdmCvf_PermitControlledTabs = 1
    EdmCvf_3StateCheckboxes = 2
    EdmCvf_RunFormulas = 4
    EdmCvf_ComputeDefaultValues = 8
    EdmCvf_VerifyValues = 16
    EdmCvf_PermitReadOnlyFields = 32
    EdmCvf_PermitComputedValues = 64
    EdmCvf_TextureBackground = 128
    EdmCvf_SearchMode = 130
    EdmCvf_Normal = 253
    EdmCvf_DisableButtons = 256
    EdmCvf_CallSaveOnCtrlReturn = 512
    EdmCvf_RunFormulasOnOpen = 1024
    EdmCvf_SerNoMenu = 1048576

class EdmCardViewUpdateType(_Enum):
    EdmCvut_EnableCtrl = 1
    EdmCvut_DisableCtrl = 2

class EdmChangeStateFileListFlag(_Enum):
    Ecsflf_GetChanged = 1
    Ecsflf_GetUnprocessed = 2
    Ecsflf_GetActionUpdated = 4

class EdmClientType(_Enum):
    Edmct_ConisioProf = 0
    Edmct_ConisioStd = 1
    Edmct_ConisioLight = 2
    Edmct_ConisioWeb = 3
    Edmct_ConisioLT = 4
    Edmct_Reserved = 5
    Edmct_None = -1

class EdmCmdNodeProp(_Enum):
    EdmCmdNode_IsTopNode = 1
    EdmCmdNode_ChildDocIDs = 2
    EdmCmdNode_ParentDocIDs = 3

class EdmCmdType(_Enum):
    EdmCmd_Menu = 1
    EdmCmd_SerialNo = 2
    EdmCmd_PreLock = 3
    EdmCmd_PostLock = 4
    EdmCmd_PreUnlock = 5
    EdmCmd_PostUnlock = 6
    EdmCmd_PreUndoLock = 7
    EdmCmd_PostUndoLock = 8
    EdmCmd_PreState = 9
    EdmCmd_PostState = 10
    EdmCmd_PreAdd = 11
    EdmCmd_PostAdd = 12
    EdmCmd_PreDelete = 13
    EdmCmd_PostDelete = 14
    EdmCmd_PreRename = 15
    EdmCmd_PostRename = 16
    EdmCmd_PreShare = 17
    EdmCmd_PostShare = 18
    EdmCmd_PreCopy = 19
    EdmCmd_PostCopy = 20
    EdmCmd_PreMove = 21
    EdmCmd_PostMove = 22
    EdmCmd_InstallAddIn = 23
    EdmCmd_UninstallAddIn = 24
    EdmCmd_PreGet = 25
    EdmCmd_PostGet = 26
    EdmCmd_PreAddFolder = 27
    EdmCmd_PostAddFolder = 28
    EdmCmd_PreDeleteFolder = 29
    EdmCmd_PostDeleteFolder = 30
    EdmCmd_PreRenameFolder = 31
    EdmCmd_PostRenameFolder = 32
    EdmCmd_PreMoveFolder = 33
    EdmCmd_PostMoveFolder = 34
    EdmCmd_PreCopyFolder = 35
    EdmCmd_PostCopyFolder = 36
    EdmCmd_CardButton = 37
    EdmCmd_CardInput = 38
    EdmCmd_CardListSrc = 39
    EdmCmd_TaskSetup = 40
    EdmCmd_TaskSetupButton = 41
    EdmCmd_TaskDetails = 42
    EdmCmd_TaskRun = 43
    EdmCmd_TaskLaunch = 44
    EdmCmd_TaskLaunchButton = 45
    EdmCmd_PreLabel = 46
    EdmCmd_PostLabel = 47
    EdmCmd_PreLabelDelete = 48
    EdmCmd_PostLabelDelete = 49
    EdmCmd_PreLabelModify = 50
    EdmCmd_PostLabelModify = 51
    EdmCmd_PreLabelAddItem = 52
    EdmCmd_PostLabelAddItem = 53

class EdmColType(_Enum):
    EdmCol_Variable = 0
    EdmCol_Name = 1
    EdmCol_FileSize = 2
    EdmCol_Date = 3
    EdmCol_LatestVersion = 4
    EdmCol_Path = 5
    EdmCol_State = 6
    EdmCol_LockUser = 7
    EdmCol_LockedIn = 8
    EdmCol_FoundInVersion = 9
    EdmCol_FileType = 10
    EdmCol_RefCount = 11
    EdmCol_Category = 12
    EdmCol_LockUserID = 13
    EdmCol_LockPath = 14
    EdmCol_LockComputer = 15
    EdmCol_StateName = 16
    EdmCol_LatestFileDate = 17
    EdmCol_LockViewID = 18
    EdmCol_Shared = 19
    EdmCol_Configuration = 21
    EdmCol_ParentFileID = 28
    EdmCol_ParentFileConfiguration = 29
    EdmCol_EdmListRetFileFlag = 30
    EdmCol_AttachedVersion = 10000

class EdmCopyFlag(_Enum):
    EdmCpy_Simple = 0
    EdmCpy_NewSerialNumbers = 1

class EdmCreateListExFlags(_Enum):
    Edmclef_Nothing = 0
    Edmclef_MayReadFiles = 1
    Edmclef_AllConfigurations = 2
    Edmclef_GetReferences = 4
    Edmclef_GetDrawings = 8
    Edmclef_AsBuilt = 16
    Edmclef_ReturnReferences = 32
    Edmclef_DontGetLatest = 64

class EdmCreateReferenceFlags(_Enum):
    Ecrf_Nothing = 0

class EdmCreateVaultFlag(_Enum):
    EdmCreateVault_Nothing = 0
    EdmCreateVault_UseDefaultAdminPassword = 1

class EdmCreateVaultViewFlag(_Enum):
    EdmCreateVaultView_Nothing = 0
    EdmCreateVaultView_SharedView = 1

class EdmDataPropertyType(_Enum):
    EdmProp_Nothing = 0
    EdmProp_ID = 1
    EdmProp_ObjectType = 2
    EdmProp_Object = 3
    EdmProp_Name = 4
    EdmProp_Path = 5
    EdmProp_Value = 6
    EdmProp_Vault = 7
    EdmProp_LinkPath = 8

class EdmDataType(_Enum):
    EdmData_Nothing = 0
    EdmData_File = 1
    EdmData_Folder = 2
    EdmData_Variable = 3
    EdmData_Link = 4

class EdmDefValComp(_Enum):
    EdmDvc_FileID = 1
    EdmDvc_FolderID = 2
    EdmDvc_FilePath = 3

class EdmDefaultValueType(_Enum):
    Edmdef_NoDefaultValue = 0
    Edmdef_TodaysDate = 1
    Edmdef_CurrentTime = 2
    Edmdef_LoggedInUserName = 3
    Edmdef_LastRevComment = 4
    Edmdef_LastTransComment = 5
    Edmdef_DocumentPath = 6
    Edmdef_LastLabel = 7
    Edmdef_CreatedByUser = 8
    Edmdef_LockedByUser = 9
    Edmdef_LastVersion = 10
    Edmdef_LastTransitionXByUser = 11
    Edmdef_CurrentStatus = 12
    Edmdef_LastVersionInStatusX = 13
    Edmdef_LastVersionInTransitionX = 14
    Edmdef_CurrentStatusDescription = 15
    Edmdef_LatestTransition = 16
    Edmdef_LatestTransitionDesc = 17
    Edmdef_Filename = 18
    Edmdef_CreatedByUserFullName = 19
    Edmdef_CreatedByUserInitials = 20
    Edmdef_CreatedByUserData = 21
    Edmdef_LockedByUserFullName = 22
    Edmdef_LockedByUserInitials = 23
    Edmdef_LockedByUserData = 24
    Edmdef_LoggedInUserFullName = 25
    Edmdef_LoggedInUserInitials = 26
    Edmdef_LoggedInUserData = 27
    Edmdef_FileNameNoExt = 28
    Edmdef_String = 1001
    Edmdef_SerialNumber = 1003
    Edmdef_FolderCardVariable = 1004
    Edmdef_FileCardVariable = 1005

class EdmFileType(_Enum):
    Edmft_Nothing = 0
    Edmft_Normal = 1
    Edmft_InternalComponent = 2
    Edmft_Item = 4
    Edmft_CutListItem = 5

class EdmFindUserProp(_Enum):
    Edmfup_LoginName = 0
    Edmfup_FullName = 1
    Edmfup_Initials = 2
    Edmfup_Email = 3
    Edmfup_UserData = 4

class EdmFolderHistoryFlag(_Enum):
    Edmfhf_Nothing = 0
    Edmfhf_Recursive = 1
    Edmfhf_IncludeFiles = 2

class EdmFolderInfoFlag(_Enum):
    Eff_Nothing = 0
    Eff_AlreadyExisted = 1
    Eff_PermissionDenied = 2

class EdmGetCmdFlags(_Enum):
    Egcf_Nothing = 0
    Egcf_AsBuilt = 1
    Egcf_Lock = 2
    Egcf_SkipUnlockedWritable = 4
    Egcf_SkipExisting = 8
    Egcf_ForPreview = 16
    Egcf_RefreshFileListing = 32
    Egcf_LockReferencedFilesToo = 64
    Egcf_AsBuiltNotDefault = 128
    Egcf_SkipOpenFileChecks = 256
    Egcf_SkipLockRefFiles = 512
    Egcf_LockNoLclCopyFiles = 1024
    Egcf_IncludeAutoCacheFiles = 2048
    Egcf_RollbackTree = 4096

class EdmGetConfirmReason(_Enum):
    Egcr_Locked = 1
    Egcr_UnlockedWritable = 2

class EdmGetFileListFlag(_Enum):
    Egflf_GetRetrieved = 1
    Egflf_GetLocked = 2
    Egflf_GetUnprocessed = 4
    Egflf_GetFailed = 8

class EdmGetFlag(_Enum):
    EdmGet_Simple = 0
    EdmGet_MakeReadOnly = 1
    EdmGet_DisableRefresh = 2
    EdmGet_Refs = 4
    EdmGet_RefsOnlyMissing = 8
    EdmGet_RefsVerLatest = 16
    EdmGet_RefsOverwriteLocked = 32
    EdmGet_ForPreview = 64

class EdmGetMenuInfoFlags(_Enum):
    Egmif_Nothing = 0
    Egmif_HasAddins = 1

class EdmGetMsgFlag(_Enum):
    EdmGetMsg_OnlyNew = 1
    EdmGetMsg_UserMessages = 2
    EdmGetMsg_Notifications = 4
    EdmGetMsg_OnlyUnread = 8

class EdmGetOpError(_Enum):
    EdmGetErr_InColdStorageAvailable = 1
    EdmGetErr_InColdStorageDeleted = 2
    EdmGetErr_InColdStoragePermissionDenied = 3
    EdmGetErr_InColdStorageRestoreFailed = 4

class EdmGetOpMsg(_Enum):
    Egom_Undefined = 0
    Egom_LockNotificationsError = 1
    Egom_UndoLockAfterErrorFailed = 2
    Egom_ErrorRunningPostAddins = 3

class EdmGetOpReply(_Enum):
    EdmGetRep_CallReportFailure = 0
    EdmGetRep_Cancel = 1
    EdmGetRep_Skip = 2
    EdmGetRep_Process = 3

class EdmGetPermFlag(_Enum):
    EdmGetPerm_Nothing = 0
    EdmGetPerm_OnlyExplicitlySet = 1

class EdmGetVarDataFlag(_Enum):
    Edmgvdf_Nothing = 0
    Edmgvdf_MayUpdate = 1

class EdmGroupDataFlags(_Enum):
    Edmgdf_Nothing = 0
    Edmgdf_GetInterface = 1
    Edmgdf_Replace = 2
    Edmgdf_ForceAdd = 4

class EdmHistoryType(_Enum):
    Edmhist_FileShare = 1
    Edmhist_FileRename = 2
    Edmhist_FileMove = 4
    Edmhist_FileRollback = 8
    Edmhist_FileDelete = 16
    Edmhist_FileUndelete = 32
    Edmhist_FileVersion = 64
    Edmhist_FileLabel = 128
    Edmhist_FileState = 256
    Edmhist_FileRevision = 512
    Edmhist_FileColdStore = 1024
    Edmhist_FolderDelete = 2048
    Edmhist_FolderUndelete = 4096
    Edmhist_FolderCreate = 8192
    Edmhist_FolderRename = 16384
    Edmhist_FolderMove = 32768
    Edmhist_FolderLabel = 65536
    Edmhist_FolderCardData = 131072
    Edmhist_ColdStoreRestore = 262144
    Edmhist_FileVerFreeVar = 524288
    Edmhist_FolderVerFreeVar = 1048576

class EdmIncRevFlags(_Enum):
    EdmIncRev_Simple = 0

class EdmInstallFileFlags(_Enum):
    EdmIff_Nothing = 0
    EdmIff_ReplaceDuplicates = 1

class EdmItemGenerationFlags(_Enum):
    Eigcf_Nothing = 0
    Eigcf_OpenItemsCheckbox = 1

class EdmItemLinkType(_Enum):
    EdmItemLnk_Dynamic = 0
    EdmItemLnk_Attachment = 1

class EdmLanguage(_Enum):
    EdmLang_Arabic = 1
    EdmLang_Bulgarian = 2
    EdmLang_Catalan = 3
    EdmLang_Chinese = 4
    EdmLang_Czech = 5
    EdmLang_Danish = 6
    EdmLang_German = 7
    EdmLang_Greek = 8
    EdmLang_English = 9
    EdmLang_Spanish = 10
    EdmLang_Finnish = 11
    EdmLang_French = 12
    EdmLang_Hebrew = 13
    EdmLang_Hungarian = 14
    EdmLang_Icelandic = 15
    EdmLang_Italian = 16
    EdmLang_Japanese = 17
    EdmLang_Korean = 18
    EdmLang_Dutch = 19
    EdmLang_Norwegian = 20
    EdmLang_Polish = 21
    EdmLang_Portuguese = 22
    EdmLang_Romanian = 24
    EdmLang_Russian = 25
    EdmLang_Serbian = 26
    EdmLang_Croatian = 26
    EdmLang_Slovak = 27
    EdmLang_Albanian = 28
    EdmLang_Swedish = 29
    EdmLang_Thai = 30
    EdmLang_Turkish = 31
    EdmLang_Urdu = 32
    EdmLang_Indonesian = 33
    EdmLang_Ukrainian = 34
    EdmLang_Belarusian = 35
    EdmLang_Slovenian = 36
    EdmLang_Estonian = 37
    EdmLang_Latvian = 38
    EdmLang_Lithuanian = 39
    EdmLang_Farsi = 41
    EdmLang_Vietnamese = 42
    EdmLang_Armenian = 43
    EdmLang_Azeri = 44
    EdmLang_Basque = 45
    EdmLang_Macedonian = 47
    EdmLang_Afrikaans = 54
    EdmLang_Georgian = 55
    EdmLang_Faeroese = 56
    EdmLang_Hindi = 57
    EdmLang_Malay = 62
    EdmLang_Kazak = 63
    EdmLang_Swahili = 65
    EdmLang_Uzbek = 67
    EdmLang_Tatar = 68
    EdmLang_Bengali = 69
    EdmLang_Punjabi = 70
    EdmLang_Gujarati = 71
    EdmLang_Oriya = 72
    EdmLang_Tamil = 73
    EdmLang_Telugu = 74
    EdmLang_Canada = 75
    EdmLang_Malayalam = 76
    EdmLang_Assamese = 77
    EdmLang_Marathi = 78
    EdmLang_Sanskrit = 79
    EdmLang_Konkani = 87
    EdmLang_Manipuri = 88
    EdmLang_Sindhi = 89
    EdmLang_Kashmiri = 96
    EdmLang_Nepali = 97

class EdmLaunchSearchFlags(_Enum):
    Elsf_Nothing = 0
    Elsf_HideTree = 1
    Elsf_HidePreview = 2
    Elsf_DefaultIsAFavorite = 4

class EdmLibVer(_Enum):
    EdmLibVer_Major = 5
    EdmLibVer_Minor = 21

class EdmLicenseType(_Enum):
    EdmLic_Editor = 1
    EdmLic_Contributor = 2
    EdmLic_Viewer = 3
    EdmLic_Processor = 4

class EdmLinkConvertFlags(_Enum):
    Elcf_Nothing = 0

class EdmListFileFlags(_Enum):
    EdmList_Nothing = 0
    EdmList_MayNotReadFile = 1
    EdmList_IsCutListItem = 2
    EdmList_IsInternalComponent = 4

class EdmListFolderFlags(_Enum):
    EdmListFolder_Nothing = 0
    EdmListFolder_Recursive = 1

class EdmListRetFileFlag(_Enum):
    EdmLstRet_Nothing = 0
    EdmLstRet_Drawing = 1
    EdmLstRet_InternalComponent = 2
    EdmLstRet_ToolboxPart = 4

class EdmLockFlag(_Enum):
    EdmLock_Simple = 0

class EdmMBoxResult(_Enum):
    EdmMbr_OK = 1
    EdmMbr_Cancel = 2
    EdmMbr_Abort = 3
    EdmMbr_Retry = 4
    EdmMbr_Ignore = 5
    EdmMbr_Yes = 6
    EdmMbr_No = 7
    EdmMbr_OkAll = 8
    EdmMbr_YesAll = 9
    EdmMbr_NoAll = 10

class EdmMBoxType(_Enum):
    EdmMbt_OKOnly = 0
    EdmMbt_OKCancel = 1
    EdmMbt_AbortRetryIgnore = 2
    EdmMbt_YesNoCancel = 3
    EdmMbt_YesNo = 4
    EdmMbt_RetryCancel = 5
    EdmMbt_Icon_Question = 32
    EdmMbt_Icon_Warning = 48
    EdmMbt_Icon_Information = 64

class EdmMenuFlags(_Enum):
    EdmMenu_Nothing = 0
    EdmMenu_MustHaveSelection = 1
    EdmMenu_OnlyFiles = 2
    EdmMenu_OnlyFolders = 4
    EdmMenu_OnlySingleSelection = 8
    EdmMenu_OnlyMultipleSelection = 16
    EdmMenu_OnlyInContextMenu = 32
    EdmMenu_NeverInContextMenu = 64
    EdmMenu_HasToolbarButton = 128
    EdmMenu_OwnerDrawToolbarButton = 256
    EdmMenu_Administration = 512
    EdmMenu_ContextMenuItem = 1024
    EdmMenu_ContextMenuItemFolder = 2048
    EdmMenu_ItemToolsMenu = 4096
    EdmMenu_HastItemToolbarButton = 8192
    EdmMenu_ShowInMenuBarAction = 16384
    EdmMenu_ShowInMenuBarModify = 32768
    EdmMenu_ShowInMenuBarDisplay = 65536
    EdmMenu_ShowInMenuBarTools = 131072

class EdmMenuStrType(_Enum):
    MenuStr_MenuStr = 1
    MenuStr_StatusBar = 2
    MenuStr_Tooltip = 3

class EdmMsgType(_Enum):
    EdmMsgType_Invalid = 0
    EdmMsgType_UserMessage = 1
    EdmMsgType_FileNotification = 2
    EdmMsgType_FolderNotification = 3
    EdmMsgType_ExternalNotification = 4

class EdmObjectType(_Enum):
    EdmObject_Invalid = 0
    EdmObject_File = 1
    EdmObject_Folder = 2
    EdmObject_State = 3
    EdmObject_Transition = 4
    EdmObject_Card = 5
    EdmObject_CardControl = 6
    EdmObject_User = 7
    EdmObject_UserGroup = 8
    EdmObject_Variable = 9
    EdmObject_Attribute = 10
    EdmObject_Label = 11
    EdmObject_Dictionary = 12
    EdmObject_Workflow = 13
    EdmObject_Category = 14
    EdmObject_BOM = 15
    EdmObject_Item = 16
    EdmObject_ItemFolder = 17
    EdmObject_ItemRootFolder = 18

class EdmProgressType(_Enum):
    Ept_Operation = 1
    Ept_FileTransfer = 2
    Ept_UpdateReference = 3

class EdmRawRefFlags(_Enum):
    Edmrrf_Nothing = 0
    Edmrrf_Ghost = 1
    Edmrrf_InternalComponent = 2

class EdmRefCbFlag(_Enum):
    EdmRefCb_GetRefInfo = 1
    EdmRefCb_OnStartCommand = 2
    EdmRefCb_OnPreFile = 4
    EdmRefCb_OnPostFile = 8
    EdmRefCb_OnEndCommand = 16

class EdmRefFlags(_Enum):
    EdmRef_File = 1
    EdmRef_Item = 2
    EdmRef_Dynamic = 4
    EdmRef_Static = 8

class EdmRefItemProperty(_Enum):
    Edmrip_ID = 0
    Edmrip_RefName = 1
    Edmrip_FileName = 2
    Edmrip_LockPath = 3
    Edmrip_LockComputer = 4
    Edmrip_LockUser = 5
    Edmrip_IncludedAs = 6
    Edmrip_FoundPath = 7
    Edmrip_VersionLocal = 8
    Edmrip_VersionLatest = 9
    Edmrip_VersionNew = 10
    Edmrip_VersionAttached = 11
    Edmrip_VersionNewAttached = 12
    Edmrip_WorkflowStateName = 13
    Edmrip_WorkflowStateIcon = 14
    Edmrip_RevisionLatest = 15
    Edmrip_RevisionNew = 16
    Edmrip_CheckLock = 17
    Edmrip_CheckUnlock = 18
    Edmrip_CheckKeepLocked = 19
    Edmrip_CheckGet = 20
    Edmrip_CheckIncRev = 21
    Edmrip_CheckUndoLock = 22
    Edmrip_CheckRemoveLocal = 23
    Edmrip_CheckCopy = 24
    Edmrip_StatusHresult = 25
    Edmrip_StatusText = 26
    Edmrip_CheckAdd = 27
    Edmrip_CheckChangeState = 28
    Edmrip_CheckOverwriteLatestVersion = 29

class EdmRefItemType(_Enum):
    Edmrit_Roots = 1
    Edmrit_All = 2

class EdmRefType(_Enum):
    Edmrt_Children = 1
    Edmrt_SubParents = 2

class EdmRefreshFlag(_Enum):
    EdmRefresh_Nothing = 0
    EdmRefresh_FileList = 1
    EdmRefresh_Hooks = 2
    EdmRefresh_Menu = 4
    EdmRefresh_Toolbar = 8

class EdmRepaintType(_Enum):
    EdmRepaint_Nothing = 0
    EdmRepaint_Repaint = 1
    EdmRepaint_Erase = 2

class EdmResolveAction(_Enum):
    Edmra_Replace = 1
    Edmra_ClearUnique = 2
    Edmra_CopySerial = 4
    Edmra_CreateSerial = 8
    Edmra_Skip = 16
    Edmra_KeepExistingSerialNumbers = 32
    Edmra_UniqueVarDelayCheck = 64
    Edmra_ForceGenerateSerial = 128

class EdmResolveReason(_Enum):
    Edmrr_DstExists = 1
    Edmrr_LockedByYouHere = 2
    Edmrr_SameAsSource = 4
    Edmrr_UniqueValues = 8
    Edmrr_SerialNumber = 16
    Edmrr_FolderExists = 32
    Edmrr_DstExistsGlobal = 64

class EdmRevComponentFlags(_Enum):
    Edmrcf_RecipientIsGroup = 1
    Edmrcf_EndOfListRestart = 2
    Edmrcf_EndOfListContinue = 4
    Edmrcf_EndOfListStop = 8
    Edmrcf_EndOfListSendMail = 16
    Edmrcf_TypeFormatString = 32
    Edmrcf_TypeList = 64

class EdmRightFlags(_Enum):
    EdmRight_None = 0
    EdmRight_Read = 1
    EdmRight_Lock = 2
    EdmRight_Delete = 4
    EdmRight_Rename = 8
    EdmRight_Add = 8
    EdmRight_Share = 16
    EdmRight_IncrementRevision = 32
    EdmRight_DeleteFolder = 64
    EdmRight_RecoverTrash = 128
    EdmRight_DestroyTrash = 256
    EdmRight_EditFolderCard = 512
    EdmRight_BomActivate = 1024
    EdmRight_MaySeeComputedBOM = 2048
    EdmRight_ChangeCard = 65536
    EdmRight_ShowWorkingVersion = 131072
    EdmRight_Rollback = 262144
    EdmRight_ColdStoreRestore = 524288
    EdmRight_EditVerFreeVarData = 1048576
    EdmRight_MoveFile = 2097152
    EdmRight_PrivateState = 4194304
    EdmRight_MoveFolder = 8388608
    EdmRight_AddFolder = 16777216
    EdmRight_RenameFolder = 16777216
    EdmRight_OverwriteLatestVersion = 33554432
    EdmRight_All = -1

class EdmSearchToken(_Enum):
    Edmstok_Recursive = 1
    Edmstok_AllVersions = 2
    Edmstok_Name = 3
    Edmstok_FolderID = 5
    Edmstok_Locked = 6
    Edmstok_Unlocked = 7
    Edmstok_LockedBy = 8
    Edmstok_VersionComment = 10
    Edmstok_VersionsByUser = 11
    Edmstok_VersionsBefore = 12
    Edmstok_VersionsAfter = 13
    Edmstok_StateName = 14
    Edmstok_StateID = 15
    Edmstok_StateHistoric = 16
    Edmstok_StateByUser = 17
    Edmstok_StateBefore = 18
    Edmstok_StateAfter = 19
    Edmstok_Label = 20
    Edmstok_LabelComment = 21
    Edmstok_LabelByUser = 22
    Edmstok_LabelBefore = 23
    Edmstok_LabelAfter = 24
    Edmstok_HistoryString = 25
    Edmstok_HistoryStringVersionComment = 26
    Edmstok_HistoryStringLabels = 27
    Edmstok_HistoryStringStateComment = 28
    Edmstok_HistoryStringRevisionComment = 29
    Edmstok_HistoryStringVariableValues = 30
    Edmstok_FindFiles = 31
    Edmstok_FindFolders = 32
    Edmstok_HistoryBefore = 33
    Edmstok_HistoryAfter = 34
    Edmstok_WorkflowName = 35
    Edmstok_ContentText = 36
    Edmstok_ContentTextInBody = 37
    Edmstok_ContentTextInProperties = 38
    Edmstok_ContentTextOr = 39
    Edmstok_ContentTextExact = 40
    Edmstok_FindItems = 41
    Edmstok_HistoryStringFileName = 42
    Edmstok_HistoryStringConfiguration = 43

class EdmStateFlags(_Enum):
    EdmState_Simple = 0
    EdmState_Refs = 1

class EdmSysPerm(_Enum):
    EdmSysPerm_None = 0
    EdmSysPerm_EditUserMgr = 1
    EdmSysPerm_EditWorkflow = 2
    EdmSysPerm_EditAddins = 4
    EdmSysPerm_MandatoryVersionComments = 8
    EdmSysPerm_MandatoryStateComments = 16
    EdmSysPerm_MandatoryMailLogin = 32
    EdmSysPerm_EditSharedSearchQuery = 64
    EdmSysPerm_ExportWebFolder = 128
    EdmSysPerm_EditTemplates = 256
    EdmSysPerm_EditReportQuery = 512
    EdmSysPerm_CanPurgeHistory = 1024
    EdmSysPerm_ModifyTasks = 1025
    EdmSysPerm_AcceptTasks = 1026
    EdmSysPerm_ModifyToolbox = 1027
    EdmSysPerm_CanAddDelLabels = 2048
    EdmSysPerm_CantIgnoreWarnings = 4096
    EdmSysPerm_ModifyCategories = 8192
    EdmSysPerm_ModifyVariables = 16384
    EdmSysPerm_ModifyRevisionNumbers = 32768
    EdmSysPerm_ModifyColumns = 65536
    EdmSysPerm_ModifyCardLists = 131072
    EdmSysPerm_ModifySerialNumbers = 262144
    EdmSysPerm_ModifyLicenseKey = 524288
    EdmSysPerm_ModifyMailCfg = 1048576
    EdmSysPerm_ModifyItemNoGen = 2097152
    EdmSysPerm_ModifyReplication = 4194304
    EdmSysPerm_ModifySearchForms = 16777216
    EdmSysPerm_ModifyTemplateForms = 33554432
    EdmSysPerm_MaySeeAdminTool = 67108864
    EdmSysPerm_RefuseLogin = 134217728
    EdmSysPerm_ModifyColdStore = 268435456
    EdmSysPerm_ModifyIndexing = 536870912
    EdmSysPerm_ModifyERPCfg = 1073741824

class EdmSysRightFlags(_Enum):
    EdmSysRight_None = 0
    EdmSysRight_EditUserMgr = 1
    EdmSysRight_EditWorkflow = 2
    EdmSysRight_EditAddins = 4
    EdmSysRight_MandatoryVersionComments = 8
    EdmSysRight_MandatoryStateComments = 16
    EdmSysRight_MandatoryMailLogin = 32
    EdmSysRight_EditSharedSearchQuery = 64
    EdmSysRight_ExportWebFolder = 128
    EdmSysRight_EditTemplates = 256
    EdmSysRight_EditReportQuery = 512
    EdmSysRight_CanPurgeHistory = 1024
    EdmSysRight_CanAddDelLabels = 2048
    EdmSysRight_CantIgnoreWarnings = 4096
    EdmSysRight_ModifyCategories = 8192
    EdmSysRight_ModifyVariables = 16384
    EdmSysRight_ModifyRevisionNumbers = 32768
    EdmSysRight_ModifyColumns = 65536
    EdmSysRight_ModifyCardLists = 131072
    EdmSysRight_ModifySerialNumbers = 262144
    EdmSysRight_ModifyLicenseKey = 524288
    EdmSysRight_ModifyMailCfg = 1048576
    EdmSysRight_ModifyItemNoGen = 2097152
    EdmSysRight_ModifyReplication = 4194304
    EdmSysRight_ModifySearchForms = 16777216
    EdmSysRight_ModifyTemplateForms = 33554432
    EdmSysRight_MaySeeAdminTool = 67108864
    EdmSysRight_RefuseLogin = 134217728
    EdmSysRight_ModifyColdStore = 268435456
    EdmSysRight_ModifyIndexing = 536870912
    EdmSysRight_ModifyERPCfg = 1073741824

class EdmTaskFlag(_Enum):
    EdmTask_Nothing = 0
    EdmTask_SupportsInitForm = 1
    EdmTask_SupportsInitExec = 2
    EdmTask_SupportsDetails = 4
    EdmTask_SupportsScheduling = 8
    EdmTask_SupportsChangeState = 16

class EdmTaskStatus(_Enum):
    EdmTaskStat_Starting = 2
    EdmTaskStat_Running = 3
    EdmTaskStat_Retrying = 4
    EdmTaskStat_Suspended = 5
    EdmTaskStat_CancelPending = 6
    EdmTaskStat_DoneOK = 7
    EdmTaskStat_DoneCancelled = 8
    EdmTaskStat_DoneFailed = 9
    EdmTaskStat_SuspensionPending = 10
    EdmTaskStat_ResumePending = 11

class EdmTransitionRightFlags(_Enum):
    EdmTransitionRight_Permit = 1
    EdmTransitionRight_DisallowSequentialStateChanges = 2

class EdmTransitionType(_Enum):
    EdmTransitionType_Normal = 0
    EdmTransitionType_Automatic = 1
    EdmTransitionType_Parallel = 2

class EdmUnlockBuildTreeFlags(_Enum):
    Eubtf_Nothing = 0
    Eubtf_MayUnlock = 1
    Eubtf_MayUndoLock = 2
    Eubtf_UndoLockDefault = 4
    Eubtf_Warn_UndoLockModifiedInDlg = 8
    Eubtf_Warn_UndoLockModifiedInCb = 16
    Eubtf_RefreshFileListing = 32
    Eubtf_NoRemoveLocalCopy = 128
    Eubtf_NoCallbackDlgErrors = 256
    Eubtf_SearchForDrawings = 512
    Eubtf_SkipOpenFileChecks = 1024
    Eubtf_ShowCloseAfterCheckinOption = 2048
    Eubtf_MayUnlockWithLatest = 4096

class EdmUnlockEvent(_Enum):
    Euev_ReadingFileRefs = 1
    Euev_UnlockFile = 2
    Euev_CompressingTree = 3

class EdmUnlockEventMsg(_Enum):
    Euev_ReadingDbFileInfo = 1

class EdmUnlockFileListFlag(_Enum):
    Euflf_GetUnlocked = 1
    Euflf_GetUndoLocked = 2
    Euflf_GetUnprocessed = 4

class EdmUnlockFlag(_Enum):
    EdmUnlock_Simple = 0
    EdmUnlock_KeepLocked = 1
    EdmUnlock_RemoveLocalCopy = 2
    EdmUnlock_IgnoreCorruptFile = 4
    EdmUnlock_IgnoreRefsOutsideVault = 8
    EdmUnlock_FailOnRegenerationNeed = 16
    EdmUnlock_IgnoreRefsNotLockedByCaller = 32
    EdmUnlock_OverwriteLatestVersion = 64
    EdmUnlock_IgnoreReferences = 128

class EdmUnlockOpMsg(_Enum):
    Euom_DuplicateUniqueVar = 1
    Euom_MissingMandatoryVar = 2
    Euom_UnknownFileFormat = 3
    Euom_UndoLockModified = 4
    Euom_AdminUndoLock = 5
    Euom_LocalFileNotFound = 6
    Euom_LocalFileShareError = 7
    Euom_AdminUnlock = 8
    Euom_CircularReference = 9

class EdmUnlockOpReply(_Enum):
    Euor_OK = 0
    Euor_Cancel = 1
    Euor_ClearVar = 10
    Euor_SkipFile = 11
    Euor_Retry = 12
    Euor_Error = -1

class EdmUnlockStatusFlag(_Enum):
    Eusf_Nothing = 0
    Eusf_CloseAfterCheckinFlag = 1

class EdmUserDataExFlag(_Enum):
    Edmudex_Nothing = 0
    Edmudex_Initials = 1
    Edmudex_CompleteName = 2
    Edmudex_UserData = 4
    Edmudex_Email = 8
    Edmudex_Phone = 16
    Edmudex_CellPhone = 32
    Edmudex_PicturePath = 64
    Edmudex_WebSite1 = 128
    Edmudex_WebSite2 = 256
    Edmudex_WebSite3 = 512
    Edmudex_WebSite4 = 1024
    Edmudex_PresenceNote = 2048
    Edmudex_All = 4095

class EdmUserDataFlags(_Enum):
    Edmudf_Nothing = 0
    Edmudf_GetInterface = 1
    Edmudf_ForceAdd = 2
    Edmudf_CopySettings = 4

class EdmUserPictureFlag(_Enum):
    Edmup_Nothing = 0

class EdmUtility(_Enum):
    EdmUtil_Search = 1
    EdmUtil_BatchUpdate = 2
    EdmUtil_UserMgr = 3
    EdmUtil_WorkflowMgr = 4
    EdmUtil_CategoryMgr = 5
    EdmUtil_BatchUnlock = 6
    EdmUtil_BatchLinkConvert = 7
    EdmUtil_AddCustomRefs = 8
    EdmUtil_VariableMgr = 9
    EdmUtil_TemplateMgr = 10
    EdmUtil_SerNoGen = 11
    EdmUtil_BatchGet = 12
    EdmUtil_BatchList = 13
    EdmUtil_BatchAddFolders = 14
    EdmUtil_RawReferenceMgr = 15
    EdmUtil_BatchAdd = 16
    EdmUtil_History = 17
    EdmUtil_RevisionMgr = 18
    EdmUtil_ClearLocalCache = 19
    EdmUtil_BatchDelete = 20
    EdmUtil_HistoryUpdate = 21
    EdmUtil_BatchChangeState = 22
    EdmUtil_BatchItemGeneration = 23
    EdmUtil_BomMgr = 24
    EdmUtil_BatchItemReferenceUpdate = 25
    EdmUtil_BatchRefVars = 26
    EdmUtil_UpdateReferences = 27
    EdmUtil_FindUser = 29

class EdmVariableFlags(_Enum):
    EdmVar_Unique = 1
    EdmVar_Mandatory = 2
    EdmVar_VerFreeUpdateAll = 4
    EdmVar_VerFreeUpdateLatest = 8

class EdmVariableType(_Enum):
    EdmVarType_None = 0
    EdmVarType_Text = 1
    EdmVarType_Int = 2
    EdmVarType_Float = 3
    EdmVarType_Bool = 4
    EdmVarType_Date = 5

class EdmVaultType(_Enum):
    EdmVault_Professional = 0
    EdmVault_Standard = 1
    EdmVault_Invalid = 2
