"""FeatureWorks API constants (SolidWorks.Interop.fworks 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class fwAdvancedOptions_e(_Enum):
    fwAdvAddConstraintsToSketch = 1
    fwAdvAllowFailFeatureCreation = 2
    fwAdvAllowWizardHoleRecognition = 4

class fwAutomaticRecognitionOptions_e(_Enum):
    fwExtrudeOption = 1
    fwVolume = 2
    fwRevolve = 4
    fwHoles = 8
    fwChamfils = 16
    fwRibs = 32
    fwBaseFlange = 64
    fwSketchedBend = 128
    fwAutoEdgeFlange = 256
    fwAutoHemFlange = 512

class fwFeatureCreationOptions_e(_Enum):
    fwAddConstraintsToSketch = 1
    fwAllowFailFeatureCreation = 2

class fwInteractiveRecognitionOptions_e(_Enum):
    fwChainFeatures = 1
    fwNormalToSketch = 2
    fwRecognizeSimilar = 4

class fwPerformanceOptions_e(_Enum):
    fwDoNotPerformBodyCheck = 1
    fwDoNotPerformIntrusionCheck = 2
