"""Workgroup PDM (legacy) API constants (PDMWorks.Interop.pdmworks 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class PDMWAndOr(_Enum):
    pdmwOr = 0
    pdmwAnd = 1

class PDMWChildrenType(_Enum):
    NoChildren = 0
    FirstLevelChildren = 1
    AllChildren = 2

class PDMWConditionType(_Enum):
    pdmwIsExactly = 0
    pdmwIsNot = 1
    pdmwContains = 2
    pdmwDoesNotContain = 3
    pdmwIsEmpty = 4
    pdmwIsNotEmpty = 5
    pdmwEqualTo = 6
    pdmwNotEqualTo = 7
    pdmwGreaterThan = 8
    pdmwLessThan = 9
    pdmwGreaterThanOrEqualTo = 10
    pdmwLessThanOrEqualTo = 11

class PDMWLinkType(_Enum):
    UnknownLink = 0
    NormalLink = 1
    ForwardLink = 2
    DeletedLink = 3

class PDMWPermission(_Enum):
    None_ = 0
    ReadOnly = 1
    ReadWrite = 2

class PDMWPropertyType(_Enum):
    pdmwAllProperties = 0
    pdmwDisplayInfo = 1
    pdmwDocumentName = 2
    pdmwNumber = 3
    pdmwDescription = 4
    pdmwRevision = 5
    pdmwOwner = 6
    pdmwStatus = 7
    pdmwConfigurationName = 8
    pdmwUserDefinedProperty = 9

class PDMWRevisionOptionType(_Enum):
    Default = 0
    ReadFromFile = 1
    Other = 2
