"""Costing API constants (SolidWorks.Interop.sldcostingapi 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swcActivateBodyResult_e(_Enum):
    swcActivateBodyResult_Success = 0
    swcActivateBodyResult_GenericFailure = 1

class swcBodyStatus_e(_Enum):
    swcBodyStatus_NotAnalysed = 0
    swcBodyStatus_Analysed = 1
    swcBodyStatus_Excluded = 2
    swcBodyStatus_AssignedCustomCost = 3

class swcBodyType_e(_Enum):
    swcBodyType_SheetMetal = 0
    swcBodyType_Machined = 1
    swcBodyType_Custom = 2
    swcBodyType_Structural = 3
    swcBodyType_Undefined = 4
    swcBodyType_GeneralBody = 5

class swcCostFeatureType_e(_Enum):
    swcMachinedBodiesFolderType = 0
    swcSheetMetalBodiesFolderType = 1
    swcSetupBodyFolderType = 2
    swcStructuralBodiesFolderType = 3
    swcCustomBodiesFolderType = 4
    swcWeldingFolderType = 5
    swcCustomOperationsFolderType = 6
    swcNoCostAssignedFolderType = 7
    swcMachinedBodyItemType = 8
    swcSheetMetalBodyItemType = 9
    swcCustomBodyItemType = 10
    swcMultiBodySetupCostItem = 11
    swcSheetMetalCutPathItemType = 12
    swcSheetMetalBendsFolderType = 13
    swcSheetMetalCustomOperationsFolderType = 14
    swcSheetMetalCutPathesFolderType = 15
    swcSheetMetalLibraryFeaturesFolderType = 16
    swcSheetMetalLibraryNoCostAssignedFolderType = 17
    swcSheetMetalSetupCostFolderType = 18
    swcSheetMetalItemFeatureType = 19
    swcSheetMetalItemSetupCost = 20
    swcSheetMetalItemCustomOperation = 21
    swcMachiningChamferFeatureItemType = 22
    swcMachiningChamferOperationItemType = 23
    swcMachiningFaceAdditionalOperationItem = 24
    swcMachiningFaceFeatureItemType = 25
    swcMachiningFaceOperationItemType = 26
    swcMachiningMillFeatureItemType = 27
    swcMachiningLocalSetupCostItemType = 28
    swcMachiningMillAdditionalOperationItemType = 29
    swcMachiningMillOperationItemType = 30
    swcMachiningPatternedHoleFeatureItemType = 31
    swcMachiningPatternedHoleSubFeatureItemType = 32
    swcMachiningSetupCostFeatureItem = 33
    swcMachiningSetupCostItemType = 34
    swcMachiningSetupCostOperationItemType = 35
    swcMachiningItemCustomOperation = 36
    swcMachiningPlateCutpathItem = 37
    swcMachiningHoleFeatureItem = 38
    swcMachiningOperationHoleDrill = 39
    swcMachiningOperationHoleCDrill = 40
    swcMachiningOperationHoleTapping = 41
    swcMachiningPlateCutpathFolderType = 42
    swcMachiningCustomOperationFolderType = 43
    swcMachiningHoleOperationsFolderType = 44
    swcMachiningLibraryFeaturesFolderType = 45
    swcMachiningMillOperationsFolderType = 46
    swcMachiningTurnOperationsFolderType = 47
    swcMachiningNCAFolderType = 48
    swcMachiningSetupCostFolderType = 49
    swcMachiningVolumeFeatureItemType = 50
    swcMachiningVolumeOperationItemType = 51
    swcMachiningVolumeAdditionalOperationItem = 52
    swcMachiningLibraryFeatureType = 53
    swcMachiningEndProfileFeatureItem = 54
    swcMachiningGrooveFeatureItem = 55
    swcNoCostAssignedBody = 56
    swcMachiningFilletFeatureItem = 57
    swcMachineSetupCostSubFolderType = 58
    swcMachineOperationSetupCostSubFolderType = 59
    swcMachineCustomSetupCostSubFolderType = 60
    swcMachineSetupCostItemType = 61
    swcMachiningItemBendFeatureType = 62
    swcAdditiveFeatureType = 63
    swcWeldFeatureItemType = 64
    swcWeldOperationItemType = 65
    swcEndCutFeaturesFolderType = 66
    swcEndCutFeatureItemType = 67
    swcStructuralBodyItemType = 68
    swcGussetsFolderType = 69
    swcEndcapFolderType = 70

class swcCostingType_e(_Enum):
    swcCostingType_Common = 0
    swcCostingType_SheetMetal = 1
    swcCostingType_Machining = 2
    swcCostingType_Structural = 3

class swcCustomStockCostInfoType_e(_Enum):
    swcCustomStockCostType_Unknown = 0
    swcCustomStockCostType_SavedCostingData = 1
    swcCustomStockCostType_Volume = 2
    swcCustomStockCostType_CustomCost = 3

class swcCustomStockImportType_e(_Enum):
    swcCustomStockImportType_Unknown = 0
    swcCustomStockImportType_Configuration = 1
    swcCustomStockImportType_ReferencePart = 2

class swcDefaultMachiningTool_e(_Enum):
    swcDefaultMachiningTool_FlatEndMill = 0
    swcDefaultMachiningTool_BallEndMill = 1
    swcDefaultMachiningTool_FaceMill = 2
    swcDefaultMachiningTool_HSSDrill = 3
    swcDefaultMachiningTool_CarbideDrill = 4
    swcDefaultMachiningTool_ODTurning = 5
    swcDefaultMachiningTool_IDTurning = 6

class swcFinishingOperationType_e(_Enum):
    swcFinishingOperationType_Roughing = 0
    swcFinishingOperationType_Semifinishing = 1
    swcFinishingOperationType_Finishing = 2

class swcLengthUnit_e(_Enum):
    swcLengthUnit_mm = 0
    swcLengthUnit_inch = 1

class swcMarkUpType_e(_Enum):
    swcMarkUpType_TotalCost = 0
    swcMarkUpType_MaterialCost = 1
    swcMarkUpType_None = 2

class swcMassUnit_e(_Enum):
    swcMassUnit_kg = 0
    swcMassUnit_lb = 1

class swcMethodType_e(_Enum):
    swcMethodType_Sheetmetal = 0
    swcMethodType_Machining = 1
    swcMethodType_Structural = 2
    swcMethodType_Plastic = 3
    swcMethodType_Casting = 4
    swcMethodType_3dPrinting = 5
    swcMethodType_MachinedPlate = 6

class swcMoldCalculationMethod_e(_Enum):
    swcMoldCalculationMethod_WallThickness = 0
    swcMoldCalculationMethod_CycleTime = 1

class swcPlane_e(_Enum):
    swcPlane_XY = 0
    swcPlane_YZ = 1
    swcPlane_XZ = 2

class swcRemovedMaterialProcessingType_e(_Enum):
    swcProcessingType_Standard = 0
    swcProcessingType_Volume = 1

class swcRunnerSystem_e(_Enum):
    swcRunnerSystem_HotRunner = 0
    swcRunnerSystem_ColdRunner = 1

class swcSheetMetalBlankSizeType_e(_Enum):
    swcSheetMetalBlankSizeType_BoundingBox = 0
    swcSheetMetalBlankSizeType_FlatPattern = 1
    swcSheetMetalBlankSizeType_CustomSize = 2
    swcSheetMetalBlankSizeType_CustomArea = 3

class swcSlotFeatureRecognitionType_e(_Enum):
    swcSlotFeatureRecognitionType_Slot = 0
    swcSlotFeatureRecognitionType_Volume = 1

class swcStockType_e(_Enum):
    swcStockType_Unknown = 0
    swcStockType_Block = 1
    swcStockType_Plate = 2
    swcStockType_Cylinder = 3
    swcStockType_Custom = 4

class swcStructuralStockCostType_e(_Enum):
    swcStructuralStockCostType_Unknown = 0
    swcStructuralStockCostType_PerLength = 1
    swcStructuralStockCostType_PerUnitLength = 2

class swcUnitSystem_e(_Enum):
    swcUnitSystem_mm_kg = 0
    swcUnitSystem_inch_lb = 1

class swcUpdateCostError_e(_Enum):
    swcUpdateCostError_None = 0
    swcUpdateCostError_TemplateUnavailable = 1
    swcUpdateCostError_MaterialUnavailable = 2

class swcVolumeFeatureCalculationType_e(_Enum):
    swcVolumeFeatureCalculationType_MachiningOperation = 0
    swcVolumeFeatureCalculationType_CostPerVolume = 1
