"""Sustainability API constants (SolidWorks.Interop.sustainability 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swSustainabilityDurationType_e(_Enum):
    swSustainabilityYear = 1
    swSustainabilityMonth = 2
    swSustainabilityDay = 3
    swSustainabilityHour = 4

class swSustainabilityEnergyType_e(_Enum):
    swSustainabilityElectricity = 0
    swSustainabilityNaturalGas = 1
    swSustainabilityDiesel = 2
    swSustainabilityGasoline = 3
    swSustainabilityKerosene = 4
    swSustainabilityLightFuelOil = 5
    swSustainabilityNone = -1

class swSustainabilityErrors_e(_Enum):
    swSustainabilityUnkownError = 0
    swSustainabilityNoData = 1
    swSustainabilityNoError = 2

class swSustainabilityFuelType_e(_Enum):
    swSustainabilityFuelElectricity = 0
    swSustainabilityFuelNaturalGas = 1
    swSustainabilityFuelNone = -1

class swSustainabilityManufacturingPaintType_e(_Enum):
    swSustainabilityWaterbasedPaint = 0
    swSustainabilitySolventbasedPaint = 1
    swSustainabilityNoPaint = -1

class swSustainabilityManufacturingProcessType_e(_Enum):
    swSustainabilityCustom = 0
    swSustainabilityDieCasted = 1
    swSustainabilityExtrusion = 2
    swSustainabilityForged = 3
    swSustainabilityMachinedSandCasting = 4
    swSustainabilityMilled = 5
    swSustainabilityManufacturingNone = 6
    swSustainabilitySandCasted = 7
    swSustainabilitySheetmetal = 8
    swSustainabilityStamped_FormedSheetmetal = 9
    swSustainabilityTurned = 10

class swSustainabilityRegionName_e(_Enum):
    swSustainabilityUnknownRegion = 0
    swSustainabilityNorthAmerica = 1
    swSustainabilityEurope = 2
    swSustainabilityAsia = 3
    swSustainabilityJapan = 4
    swSustainabilitySouthAmerica = 5
    swSustainabilityAustralia = 6
    swSustainabilityIndia = 7
    swSustainabilityNumElems = 8

class swSustainabilitySaveAsFileType_e(_Enum):
    swSustainabilityDocxReport = 1
    swSustainabilitySpreadsheet = 2
    swSustainabilityGabiInputFile = 3
