"""3D printing API constants (SolidWorks.Interop.sw3dprinter 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class ConfigureControls_e(_Enum):
    DisablePrintQualitySpecifyInAdvancedOption = 1
    DisableOrientationMinimumBuildTimeOption = 2
    DisableOrientationBestSurfaceQualityOption = 4
    DisableOrientationSpecifyInAdvancedOption = 8
    DisableAdvancedSettingsButton = 16
    DisableCostField = 32
    DisableQuantityControl = 64
    DisableUpdateStatisticsButton = 128
    OkButtonAlwaysEnabled = 256

class ConfigureDialog_e(_Enum):
    DisablePrintQualitySpecifyInAdvancedOption = 1
    DisableOrientationMinimumBuildTimeOption = 2
    DisableOrientationBestSurfaceQualityOption = 4
    DisableOrientationSpecifyInAdvancedOption = 8
    DisableAdvancedSettingsButton = 16
    DisableCostField = 32
    DisableQuantityControl = 64
    DisableUpdateStatisticsButton = 128
    OkButtonAlwaysEnabled = 256

class sw3Dorientation_e(_Enum):
    BestQuality = 1
    MiniumTime = 2
    Manual = 3

class swBuildEnvelopeStartingPoint_e(_Enum):
    swBuildEnvelopeStartingPoint_e_Minimum = 1
    swBuildEnvelopeStartingPoint_e_Maximum = 2

class swBuildOrientation_e(_Enum):
    swBuildOrientation_e_Default = 1
    swBuildOrientation_e_BestQualty = 2
    swBuildOrientation_e_FastestBuildTime = 3
    swBuildOrientation_e_OrthogonalPlusRotation = 4
    swBuildOrientation_e_VendorSpecifiedInAdvancedProperties = 5

class swDataChangeResult_e(_Enum):
    swDataChangeResult_e_DataChangeSuccess = 1
    swDataChangeResult_e_DataChangeFailure = 2

class swManual3DprintOrientation_e(_Enum):
    Front = 1
    Back = 2
    Top = 3
    Bottom = 4
    Left = 5
    Right = 6

class swPrintQuality_e(_Enum):
    swPrintQuality_e_Default = 1
    swPrintQuality_e_Draft = 2
    swPrintQuality_e_Normal = 3
    swPrintQuality_e_Fine = 4
    swPrintQuality_e_VendorSpecifiedInAdvancedProperties = 5

class swPrintResult_e(_Enum):
    swPrintResult_e_PrintSuccess = 1
    swPrintResult_e_PrintFailure = 2

class swPrinterStatus_e(_Enum):
    swPrinterStatus_e_Available = 1
    swPrinterStatus_e_Busy = 2
    swPrinterStatus_e_Offline = 3
    swPrinterStatus_e_Error = 4
    swPrinterStatus_e_Other = 5

class swStartupResult_e(_Enum):
    swStartupResult_e_StartupOk = 1
    swStartupResult_e_CouldNotSetDefaults = 2
