"""Design Library browser API constants (SolidWorks.Interop.swbrowser 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swApplicationEvents_e(_Enum):
    swDestroy = 1

class swPDMDocManagerEvents_e(_Enum):
    swPDMDestroy = 1
    swBeforeWritingToDocument = 2
    swAfterWritingToDocument = 3
    swPreInsertDocument = 4
    swNewDocumentAdded = 5
    swBeforeDeletingDocument = 6
    swAfterDeletingDocument = 7
    swBeforeCopyingDocument = 8
    swAfterCopyingDocument = 9

class swPDMStatus_e(_Enum):
    swPDMStatusError = 0
    swPDMStatusUnknown = 1
    swPDMStatusKnownAndAvailable = 2
    swPDMStatusKnownAndUnavailable = 3
