"""DimXpert API constants (SolidWorks.Interop.swdimxpert 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swDimXpertAnnotationType_e(_Enum):
    swDimXpertAnnotationType_unknown = 0
    swDimXpertDimTol_DistanceBetween = 101
    swDimXpertDimTol_CounterBore = 102
    swDimXpertDimTol_Depth = 103
    swDimXpertDimTol_CounterSinkDiameter = 104
    swDimXpertDimTol_ChamferDimension = 105
    swDimXpertDimTol_AngleBetween = 106
    swDimXpertDimTol_CounterSinkAngle = 107
    swDimXpertDimTol_ConeAngle = 108
    swDimXpertDimTol_Diameter = 109
    swDimXpertDimTol_Length = 110
    swDimXpertDimTol_Radius = 111
    swDimXpertDimTol_Width = 112
    swDimXpertDimTol_CompositeDistanceBetween = 113
    swDimXpertDimTol_PatternAngleBetween = 114
    swDimXpertDatum = 150
    swDimXpertGeoTol_Position = 201
    swDimXpertGeoTol_CompositePosition = 202
    swDimXpertGeoTol_Symmetry = 203
    swDimXpertGeoTol_Concentricity = 204
    swDimXpertGeoTol_LineProfile = 205
    swDimXpertGeoTol_CompositeLineProfile = 206
    swDimXpertGeoTol_SurfaceProfile = 207
    swDimXpertGeoTol_CompositeSurfaceProfile = 208
    swDimXpertGeoTol_Angularity = 210
    swDimXpertGeoTol_Parallelism = 211
    swDimXpertGeoTol_Perpendicularity = 212
    swDimXpertGeoTol_TotalRunout = 213
    swDimXpertGeoTol_CircularRunout = 214
    swDimXpertGeoTol_Flatness = 215
    swDimXpertGeoTol_Circularity = 216
    swDimXpertGeoTol_Cylindricity = 217
    swDimXpertGeoTol_Straightness = 218
    swDimXpertGeoTol_Tangency = 219

class swDimXpertAutoDimSchemePartType_e(_Enum):
    swDimXpertAutoDimSchemePartType_Prismatic = 0
    swDimXpertAutoDimSchemePartType_Turned = 1

class swDimXpertAutoDimSchemePatternType_e(_Enum):
    swDimXpertAutoDimSchemePatternType_Linear = 0
    swDimXpertAutoDimSchemePatternType_Polar = 1

class swDimXpertAutoDimSchemeToleranceType_e(_Enum):
    swDimXpertAutoDimSchemeToleranceType_PlusMinus = 0
    swDimXpertAutoDimSchemeToleranceType_Geometric = 1

class swDimXpertBlockToleranceType_e(_Enum):
    swDimXpertBlockToleranceType_unknown = 0
    swDimXpertBlockToleranceType_ASMEInch = 1
    swDimXpertBlockToleranceType_ISO2768 = 2

class swDimXpertChamferAngleType_e(_Enum):
    swDimXpertChamferAngleType_unknown = 0
    swDimXpertChamferAngleType_Concave = 1
    swDimXpertChamferAngleType_Convex = 2

class swDimXpertChamferDimensionType_e(_Enum):
    swDimXpertChamferDimensionType_unknown = 0
    swDimXpertChamferDimensionType_Angle = 1
    swDimXpertChamferDimensionType_LinearDistance1 = 2
    swDimXpertChamferDimensionType_LinearDistance2 = 3

class swDimXpertChamferType_e(_Enum):
    swDimXpertChamferType_unknown = 0
    swDimXpertChamferType_DistanceAngle = 1
    swDimXpertChamferType_DistanceDistance = 2
    swDimXpertChamferType_Vertex = 3

class swDimXpertCombineAnnotation_e(_Enum):
    swDimXpertCombineAnnotation_swDimXpertCombineFailed = 0
    swDimXpertCombineAnnotation_swDimXpertCombineSucceeded = 1
    swDimXpertCombineAnnotation_swDimXpertBreakFailed = 2
    swDimXpertCombineAnnotation_swDimXpertBreakSucceeded = 3

class swDimXpertCompoundHoleType_e(_Enum):
    swDimXpertCompoundHoleType_unknown = 0
    swDimXpertCompoundHoleType_Compound = 1
    swDimXpertCompoundHoleType_Counterbore = 2
    swDimXpertCompoundHoleType_Countersink = 3
    swDimXpertCompoundHoleType_Simple = 4

class swDimXpertDimensionPositionOption_e(_Enum):
    swDimXpertDimensionPositionOption_N = 0
    swDimXpertDimensionPositionOption_X = 1
    swDimXpertDimensionPositionOption_Y = 2
    swDimXpertDimensionPositionOption_Z = 3

class swDimXpertDimensionToleranceType_e(_Enum):
    swDimXpertDimensionToleranceType_unknown = 0
    swDimXpertDimTolType_BlockTolerance = 1
    swDimXpertDimTolType_BlockToleranceNoNominal = 2
    swDimXpertDimTolType_ISOLimitsAndFits = 3
    swDimXpertDimTolType_ISOLimitsAndFitsNoNominal = 4
    swDimXpertDimTolType_LimitDimension = 5
    swDimXpertDimTolType_MAXTolerance = 6
    swDimXpertDimTolType_MINTolerance = 7
    swDimXpertDimTolType_NoTolerance = 8
    swDimXpertDimTolType_PlusMinusDimension = 9
    swDimXpertDimTolType_PlusMinusNoNominal = 10

class swDimXpertDistanceFosUsage_e(_Enum):
    swDimXpertDistanceFosUsage_unknown = 0
    swDimXpertDistanceFosUsage_Center = 1
    swDimXpertDistanceFosUsage_MaximumSide = 2
    swDimXpertDistanceFosUsage_MinimumSide = 3

class swDimXpertFeatureFilters_e(_Enum):
    swDimXpertFeatureFilters_Plane = 1
    swDimXpertFeatureFilters_Surface = 2
    swDimXpertFeatureFilters_Cone = 4
    swDimXpertFeatureFilters_Cylinder = 8
    swDimXpertFeatureFilters_Boss = 16
    swDimXpertFeatureFilters_Fillet = 32
    swDimXpertFeatureFilters_Chamfer = 64
    swDimXpertFeatureFilters_SimpleHole = 128
    swDimXpertFeatureFilters_Counterbore = 256
    swDimXpertFeatureFilters_Countersink = 512
    swDimXpertFeatureFilters_Slot = 1024
    swDimXpertFeatureFilters_Notch = 2048
    swDimXpertFeatureFilters_Pocket = 4096
    swDimXpertFeatureFilters_SurfOfRev = 8192
    swDimXpertFeatureFilters_Torus = 16384

class swDimXpertFeatureSelectorOption_e(_Enum):
    swDimXpertFeatureSelectorOption_Plane = 0
    swDimXpertFeatureSelectorOption_Cylinder = 1
    swDimXpertFeatureSelectorOption_Sphere = 2
    swDimXpertFeatureSelectorOption_Freeform = 3
    swDimXpertFeatureSelectorOption_Cone = 4
    swDimXpertFeatureSelectorOption_SimpleHole = 5
    swDimXpertFeatureSelectorOption_Slot = 6
    swDimXpertFeatureSelectorOption_Width = 7
    swDimXpertFeatureSelectorOption_Boss = 8
    swDimXpertFeatureSelectorOption_Tab = 9
    swDimXpertFeatureSelectorOption_Fillet = 10
    swDimXpertFeatureSelectorOption_Chamfer = 11
    swDimXpertFeatureSelectorOption_ConicalHole = 12
    swDimXpertFeatureSelectorOption_Pocket = 13
    swDimXpertFeatureSelectorOption_Notch = 14
    swDimXpertFeatureSelectorOption_Extrude = 15
    swDimXpertFeatureSelectorOption_SplitPlane = 16
    swDimXpertFeatureSelectorOption_SplitCylinder = 17
    swDimXpertFeatureSelectorOption_CntrBore = 18
    swDimXpertFeatureSelectorOption_CntrSink = 19
    swDimXpertFeatureSelectorOption_CompoundHole = 20
    swDimXpertFeatureSelectorOption_HolePattern = 21
    swDimXpertFeatureSelectorOption_Pattern = 22
    swDimXpertFeatureSelectorOption_MixedPattern = 23
    swDimXpertFeatureSelectorOption_Default = -1

class swDimXpertFeatureType_e(_Enum):
    swDimXpertFeatureType_unknown = 0
    swDimXpertFeature_Plane = 1
    swDimXpertFeature_Cylinder = 2
    swDimXpertFeature_Cone = 3
    swDimXpertFeature_Extrude = 4
    swDimXpertFeature_Fillet = 5
    swDimXpertFeature_Chamfer = 6
    swDimXpertFeature_CompoundHole = 7
    swDimXpertFeature_CompoundWidth = 8
    swDimXpertFeature_CompoundNotch = 9
    swDimXpertFeature_CompoundClosedSlot3D = 10
    swDimXpertFeature_IntersectPoint = 11
    swDimXpertFeature_IntersectLine = 12
    swDimXpertFeature_IntersectCircle = 13
    swDimXpertFeature_IntersectPlane = 14
    swDimXpertFeature_Pattern = 15
    swDimXpertFeature_Sphere = 16
    swDimXpertFeature_BestfitPlane = 17
    swDimXpertFeature_Surface = 18

class swDimXpertGtolType_e(_Enum):
    swDimXpertGtolType_Straightness = 0
    swDimXpertGtolType_Flatness = 1
    swDimXpertGtolType_Circularity = 2
    swDimXpertGtolType_Cylindricity = 3
    swDimXpertGtolType_SurfaceProfile = 4
    swDimXpertGtolType_LineProfile = 5
    swDimXpertGtolType_Angularity = 6
    swDimXpertGtolType_Perpendicularity = 7
    swDimXpertGtolType_Parallelism = 8
    swDimXpertGtolType_Position = 9
    swDimXpertGtolType_Symmetry = 10
    swDimXpertGtolType_Concentricity = 11
    swDimXpertGtolType_CircularRunout = 12
    swDimXpertGtolType_TotalRunout = 13

class swDimXpertISO2768PartType_e(_Enum):
    swDimXpertISO2768PartType_unknown = 0
    swDimXpertISO2768PartType_Fine = 1
    swDimXpertISO2768PartType_Medium = 2
    swDimXpertISO2768PartType_Coarse = 3
    swDimXpertISO2768PartType_VeryCoarse = 4

class swDimXpertMaterialConditionModifier_e(_Enum):
    swDimXpertMaterialConditionModifier_unknown = 0
    swDimXpertMCM_LMC = 1
    swDimXpertMCM_MMC = 2
    swDimXpertMCM_NoMCM = 3
    swDimXpertMCM_RFS = 4

class swDimXpertOrientationZoneType_e(_Enum):
    swDimXpertOrientationZoneType_unknown = 0
    swDimXpertOrientationZoneType_Cylindrical = 1
    swDimXpertOrientationZoneType_Planar = 2

class swDimXpertPatternTreatmentType_e(_Enum):
    swDimXpertPatternTreatmentType_unknown = 0
    swDimXpertPatternTreatmentType_CircularPattern = 1
    swDimXpertPatternTreatmentType_IndividualFeatures = 2

class swDimXpertPositionZoneType_e(_Enum):
    swDimXpertPositionZoneType_unknown = 0
    swDimXpertPositionZoneType_Boundary = 1
    swDimXpertPositionZoneType_CylindricalPosition = 2
    swDimXpertPositionZoneType_PlanarPosition = 3
    swDimXpertPositionZoneType_RadialPositionArc = 4
    swDimXpertPositionZoneType_RadialPositionPlanar = 5
    swDimXpertPositionZoneType_SphericalPosition = 6

class swDimXpertStraightnessZoneType_e(_Enum):
    swDimXpertStraightnessZoneType_unknown = 0
    swDimXpertStraightnessZoneType_Cylindrical = 1
    swDimXpertStraightnessZoneType_PlanarMedian = 2
    swDimXpertStraightnessZoneType_Surface = 3
