"""Document Manager (needs a licence key) API constants (SolidWorks.Interop.swdocumentmgr 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class SwDMConfigurationError(_Enum):
    SwDMConfigurationError_None = 0
    SwDMConfigurationError_Unknown = 1
    SwDMConfigurationError_RequiredArgumentNull = 2
    SwDMConfigurationError_ComObjectDisconnected = 3
    SwDMConfigurationError_NameNotFound = 4
    SwDMConfigurationError_DataMissing = 5

class SwDMDocumentLicenseType_e(_Enum):
    swDMDocLicenseType_Unknown = 0
    swDMDocLicenseType_Commerical = 1
    swDMDocLicenseType_NonCommercial = 2

class SwDmBodyError(_Enum):
    swDmBodyErrorNone = 0
    swDmBodyErrorGetCountNotCalled = 1
    swDmBodyErrorInvalidStorage = 2
    swBodyErrorNoData = 4
    swBodyErrorFileCreation = 8
    swBodyErrorDecompression = 16

class SwDmColumnType(_Enum):
    swDmColumnTypeZone = 0
    swDmColumnTypeRevision = 1
    swDmColumnTypeDescription = 2
    swDmColumnTypeDate = 3
    swDmColumnTypeApproved = 4
    swDmColumnTypeUser = 5
    swDmColumnTypeConfigQty = 6
    swDmColumnTypeItemNumber = 7
    swDmColumnTypePartNumber = 8
    swDmColumnTypeNotFound = -1

class SwDmCopyOptions(_Enum):
    swDmCopyOptionsOverwriteExistingDocs = 1
    swDmCopyOptionsCreateNewFolder = 2

class SwDmCustomInfoType(_Enum):
    swDmCustomInfoUnknown = 0
    swDmCustomInfoNumber = 3
    swDmCustomInfoYesOrNo = 11
    swDmCustomInfoText = 30
    swDmCustomInfoDate = 64

class SwDmDesignTableDataError(_Enum):
    swDmDesignTableDataError_ExternalTableFound = 0
    swDmDesignTableDataError_InternalTable = 1
    swDmDesignTableDataError_NoTable = 2
    swDMDesigTableDataError_ExternalTableNotFound = 3
    swDmDesignTableDataError_NoData = 4
    swDmDesignTableDataError_Fail = 5

class SwDmDocumentOpenError(_Enum):
    swDmDocumentOpenErrorNone = 0
    swDmDocumentOpenErrorFail = 1
    swDmDocumentOpenErrorNonSW = 2
    swDmDocumentOpenErrorFileNotFound = 3
    swDmDocumentOpenErrorFileReadOnly = 4
    swDmDocumentOpenErrorNoLicense = 5
    swDmDocumentOpenErrorFutureVersion = 6

class SwDmDocumentSaveError(_Enum):
    swDmDocumentSaveErrorNone = 0
    swDmDocumentSaveErrorReadOnly = 1
    swDmDocumentSaveErrorFail = 2

class SwDmDocumentType(_Enum):
    swDmDocumentUnknown = 0
    swDmDocumentPart = 1
    swDmDocumentAssembly = 2
    swDmDocumentDrawing = 3

class SwDmEDwgDataError(_Enum):
    swDmEDwgDataErrorNone = 0
    swDmEDwgDataErrorNoData = 1
    swDmEDwgDataErrorFileCreation = 2
    swDmEDwgDataErrorInvalidStorage = 4

class SwDmMassPropError(_Enum):
    swDmMassPropErrorNone = 0
    swDmMassPropErrorEarlierVersion = 1
    swDmMassPropErrorNoData = 2
    swDmMassPropErrorUnknown = 3

class SwDmMoveCopyError(_Enum):
    swDmMoveCopyErrorNone = 0
    swDmMoveCopyErrorSourceDoesNotExist = 1
    swDmMoveCopyErrorFail = 2

class SwDmPreviewError(_Enum):
    swDmPreviewErrorNone = 0
    swDmPreviewErrorFileOpen = 1
    swDmPreviewErrorNoPreview = 2
    swDmPreviewErrorMakeBmpFail = 4

class SwDmReferenceStatus(_Enum):
    swDmReferenceStatusUnknown = 0
    swDmReferenceStatusBroken = 1
    swDmReferenceStatusNotBroken = 2

class SwDmSearchFilters(_Enum):
    SwDmSearchSubfolders = 1
    SwDmSearchForPart = 2
    SwDmSearchForDrawing = 4
    SwDmSearchForAssembly = 8
    SwDmSearchExternalReference = 16
    SwDmSearchInContextReference = 32
    SwDmSearchRootAssemblyFolder = 64

class SwDmTableError(_Enum):
    SwDmTableErrorNone = 0
    SwDmTableErrorFailed = 1
    SwDmTableErrorNotSupported = 2

class SwDmTableHeaderStyle(_Enum):
    SwDmTableHeaderStyleTop = 0
    SwDmTableHeaderStyleBottom = 1
    SwDmTableHeaderStyleNotFound = 2

class SwDmTableType(_Enum):
    swDmTableTypeUnsupported = 0
    swDmTableTypeRevision = 1
    swDmTableTypeBOM = 2
    swDmTableTypeBOMHidden = 3

class SwDmToolboxPartType(_Enum):
    swDmNotAToolboxPart = 0
    swDmToolboxStandardPart = 1
    swDmToolboxCopiedPart = 2

class SwDmWhereUsedOptions(_Enum):
    SwDmSearchSubfolders = 1
    SwDmSearchForPart = 2
    SwDmSearchForDrawing = 4
    SwDmSearchForAssembly = 8
    SwDmSearchExternalReference = 16
    SwDmSearchInContextReference = 32
    SwDmSearchRootAssemblyFolder = 64

class SwDmXmlDataError(_Enum):
    swDmXmlDataErrorNone = 0
    swDmXmlDataErrorNoData = 1
    swDmXmlDataErrorFileCreation = 2
    swDmXmlDataErrorInvalidStorage = 4
    swDmXmlDataErrorStorageOpenFail = 8

class swDMPartConfigurationGrouping(_Enum):
    swDMPartConfigurationGrouping_SeparateItemsForEachConfigurationOfPart = 1
    swDMPartConfigurationGrouping_OneItemForAllConfigurationsOfPart = 2
    swDMPartConfigurationGrouping_OneItemForPartsWithSameConfigurationName = 3

class swDmAngleUnit_e(_Enum):
    swDmAngleUnit_swDmDegrees = 0
    swDmAngleUnit_swDmDegreesMinutes = 1
    swDmAngleUnit_swDmDegreesMinutesSeconds = 2
    swDmAngleUnit_swDmRadians = 3

class swDmBOMPartNumberSource(_Enum):
    swDmBOMPartNumber_DocumentName = 0
    swDmBOMPartNumber_ConfigurationName = 1
    swDmBOMPartNumber_ParentName = 2
    swDmBOMPartNumber_UserSpecified = 3
    swDmBOMPartNumber_NotDefined = -1

class swDmBOMTableType(_Enum):
    swDmBOMTableTypePartsOnly = 0
    swDmBOMTableTypeTopLevelOnly = 1
    swDmBOMTableTypeIndented = 2

class swDmConfigurationType(_Enum):
    swDmConfiguration_Standard = 0
    swDmConfiguration_AsMachined = 1
    swDmConfiguration_AsWelded = 2
    swDmConfiguration_SheetMetal = 3
    swDmConfiguration_SpeedPak = 4

class swDmDimXpertAnnotationType_e(_Enum):
    swDmDimXpertAnnotationType_unknown = 0
    swDmDimXpertDimTol_DistanceBetween = 101
    swDmDimXpertDimTol_CounterBore = 102
    swDmDimXpertDimTol_Depth = 103
    swDmDimXpertDimTol_CounterSinkDiameter = 104
    swDmDimXpertDimTol_ChamferDimension = 105
    swDmDimXpertDimTol_AngleBetween = 106
    swDmDimXpertDimTol_CounterSinkAngle = 107
    swDmDimXpertDimTol_ConeAngle = 108
    swDmDimXpertDimTol_Diameter = 109
    swDmDimXpertDimTol_Length = 110
    swDmDimXpertDimTol_Radius = 111
    swDmDimXpertDimTol_Width = 112
    swDmDimXpertDimTol_CompositeDistanceBetween = 113
    swDmDimXpertDimTol_PatternAngleBetween = 114
    swDmDimXpertDatum = 150
    swDmDimXpertGeoTol_Position = 201
    swDmDimXpertGeoTol_CompositePosition = 202
    swDmDimXpertGeoTol_Symmetry = 203
    swDmDimXpertGeoTol_Concentricity = 204
    swDmDimXpertGeoTol_LineProfile = 205
    swDmDimXpertGeoTol_CompositeLineProfile = 206
    swDmDimXpertGeoTol_SurfaceProfile = 207
    swDmDimXpertGeoTol_CompositeSurfaceProfile = 208
    swDmDimXpertGeoTol_Angularity = 210
    swDmDimXpertGeoTol_Parallelism = 211
    swDmDimXpertGeoTol_Perpendicularity = 212
    swDmDimXpertGeoTol_TotalRunout = 213
    swDmDimXpertGeoTol_CircularRunout = 214
    swDmDimXpertGeoTol_Flatness = 215
    swDmDimXpertGeoTol_Circularity = 216
    swDmDimXpertGeoTol_Cylindricity = 217
    swDmDimXpertGeoTol_Straightness = 218
    swDmDimXpertGeoTol_Tangency = 219

class swDmDimXpertBlockToleranceType_e(_Enum):
    swDmDimXpertBlockToleranceType_unknown = 0
    swDmDimXpertBlockToleranceType_ASMEInch = 1
    swDmDimXpertBlockToleranceType_ISO2768 = 2

class swDmDimXpertChamferAngleType_e(_Enum):
    swDmDimXpertChamferAngleType_unknown = 0
    swDmDimXpertChamferAngleType_Concave = 1
    swDmDimXpertChamferAngleType_Convex = 2

class swDmDimXpertChamferDimensionType_e(_Enum):
    swDmDimXpertChamferDimensionType_unknown = 0
    swDmDimXpertChamferDimensionType_Angle = 1
    swDmDimXpertChamferDimensionType_LinearDistance1 = 2
    swDmDimXpertChamferDimensionType_LinearDistance2 = 3

class swDmDimXpertChamferType_e(_Enum):
    swDmDimXpertChamferType_unknown = 0
    swDmDimXpertChamferType_DistanceAngle = 1
    swDmDimXpertChamferType_DistanceDistance = 2
    swDmDimXpertChamferType_Vertex = 3

class swDmDimXpertDimensionToleranceType_e(_Enum):
    swDmDimXpertDimensionToleranceType_unknown = 0
    swDmDimXpertDimTolType_BlockTolerance = 1
    swDmDimXpertDimTolType_BlockToleranceNoNominal = 2
    swDmDimXpertDimTolType_ISOLimitsAndFits = 3
    swDmDimXpertDimTolType_ISOLimitsAndFitsNoNominal = 4
    swDmDimXpertDimTolType_LimitDimension = 5
    swDmDimXpertDimTolType_MAXTolerance = 6
    swDmDimXpertDimTolType_MINTolerance = 7
    swDmDimXpertDimTolType_NoTolerance = 8
    swDmDimXpertDimTolType_PlusMinusDimension = 9
    swDmDimXpertDimTolType_PlusMinusNoNominal = 10

class swDmDimXpertDistanceFosUsage_e(_Enum):
    swDmDimXpertDistanceFosUsage_unknown = 0
    swDmDimXpertDistanceFosUsage_Center = 1
    swDmDimXpertDistanceFosUsage_MaximumSide = 2
    swDmDimXpertDistanceFosUsage_MinimumSide = 3

class swDmDimXpertFeatureType_e(_Enum):
    swDmDimXpertFeatureType_unknown = 0
    swDmDimXpertFeature_Plane = 1
    swDmDimXpertFeature_Cylinder = 2
    swDmDimXpertFeature_Cone = 3
    swDmDimXpertFeature_Extrude = 4
    swDmDimXpertFeature_Fillet = 5
    swDmDimXpertFeature_Chamfer = 6
    swDmDimXpertFeature_CompoundHole = 7
    swDmDimXpertFeature_CompoundWidth = 8
    swDmDimXpertFeature_CompoundNotch = 9
    swDmDimXpertFeature_CompoundClosedSlot3D = 10
    swDmDimXpertFeature_IntersectPoint = 11
    swDmDimXpertFeature_IntersectLine = 12
    swDmDimXpertFeature_IntersectCircle = 13
    swDmDimXpertFeature_IntersectPlane = 14
    swDmDimXpertFeature_Pattern = 15
    swDmDimXpertFeature_Sphere = 16
    swDmDimXpertFeature_BestfitPlane = 17
    swDmDimXpertFeature_Surface = 18

class swDmDimXpertISO2768PartType_e(_Enum):
    swDmDimXpertISO2768PartType_unknown = 0
    swDmDimXpertISO2768PartType_Fine = 1
    swDmDimXpertISO2768PartType_Medium = 2
    swDmDimXpertISO2768PartType_Coarse = 3
    swDmDimXpertISO2768PartType_VeryCoarse = 4

class swDmDimXpertMaterialConditionModifier_e(_Enum):
    swDmDimXpertMaterialConditionModifier_unknown = 0
    swDmDimXpertMCM_LMC = 1
    swDmDimXpertMCM_MMC = 2
    swDmDimXpertMCM_NoMCM = 3
    swDmDimXpertMCM_RFS = 4

class swDmDimXpertOrientationZoneType_e(_Enum):
    swDmDimXpertOrientationZoneType_unknown = 0
    swDmDimXpertOrientationZoneType_Cylindrical = 1
    swDmDimXpertOrientationZoneType_Planar = 2

class swDmDimXpertPatternTreatmentType_e(_Enum):
    swDmDimXpertPatternTreatmentType_unknown = 0
    swDmDimXpertPatternTreatmentType_CircularPattern = 1
    swDmDimXpertPatternTreatmentType_IndividualFeatures = 2

class swDmDimXpertPositionZoneType_e(_Enum):
    swDmDimXpertPositionZoneType_unknown = 0
    swDmDimXpertPositionZoneType_Boundary = 1
    swDmDimXpertPositionZoneType_CylindricalPosition = 2
    swDmDimXpertPositionZoneType_PlanarPosition = 3
    swDmDimXpertPositionZoneType_RadialPositionArc = 4
    swDmDimXpertPositionZoneType_RadialPositionPlanar = 5
    swDmDimXpertPositionZoneType_SphericalPosition = 6

class swDmDimXpertStraightnessZoneType_e(_Enum):
    swDmDimXpertStraightnessZoneType_unknown = 0
    swDmDimXpertStraightnessZoneType_Cylindrical = 1
    swDmDimXpertStraightnessZoneType_PlanarMedian = 2
    swDmDimXpertStraightnessZoneType_Surface = 3

class swDmDocumentUnitsIntegerValue_e(_Enum):
    swDmUnitSystem = 0
    swDmUnitsLinear = 1
    swDmUnitsLinearDecimalDisplay = 2
    swDmUnitsLinearDecimalPlaces = 3
    swDmUnitsLinearFractionDenominator = 4
    swDmUnitsDualLinear = 5
    swDmUnitsDualLinearDecimalDisplay = 6
    swDmUnitsDualLinearDecimalPlaces = 7
    swDmUnitsDualLinearFractionDenominator = 8
    swDmUnitsAngular = 9
    swDmUnitsAngularDecimalPlaces = 10
    swDmUnitsMassPropLength = 11
    swDmUnitsMassPropDecimalPlaces = 12
    swDmUnitsMassPropMass = 13
    swDmUnitsMassPropVolume = 14
    swDmUnitsTimeUnits = 15
    swDmUnitsTimeDecimalPlaces = 16
    swDmUnitsForce = 17
    swDmUnitsForceDecimalPlaces = 18
    swDmUnitsPowerUnits = 19
    swDmUnitsPowerDecimalPlaces = 20
    swDmUnitsEnergyUnits = 21
    swDmUnitsEnergyDecimalPlaces = 22
    swDmUnitsDecimalRounding = 24

class swDmDocumentUnitsToggle_e(_Enum):
    swDmUnitsLinearFeetAndInchesFormat = 0
    swDmUnitsLinearRoundToNearestFraction = 1
    swDmUnitsDualLinearRoundToNearestFraction = 2
    swDmUnitsDualLinearFeetAndInchesFormat = 3

class swDmExcludeFromBOMResult(_Enum):
    swDmExcludeFromBOM_FALSE = 0
    swDmExcludeFromBOM_TRUE = 1
    swDmExcludeFromBOM_NotDefined = -1

class swDmFractionDisplay_e(_Enum):
    swDmFractionDisplay_swDmNone = 0
    swDmFractionDisplay_swDmDecimal = 1
    swDmFractionDisplay_swDmFraction = 2

class swDmLengthUnit_e(_Enum):
    swDmLengthUnit_swDmMillimeters = 0
    swDmLengthUnit_swDmCentimeters = 1
    swDmLengthUnit_swDmMeters = 2
    swDmLengthUnit_swDmInches = 3
    swDmLengthUnit_swDmFeet = 4
    swDmLengthUnit_swDmFeetInches = 5
    swDmLengthUnit_swDmAngstroms = 6
    swDmLengthUnit_swDmNanometers = 7
    swDmLengthUnit_swDmMicrons = 8
    swDmLengthUnit_swDmMils = 9
    swDmLengthUnit_swDmMicroInches = 10

class swDmRevTableStyle(_Enum):
    swDmRevSeeSheet1 = 0
    swDmRevCopyOfSheet1 = 1
    swDmRevIndependent = 2
    swDmRevStyleUnknown = -1

class swDmShowChildComponentsInBOMResult(_Enum):
    swDmShowChildComponentsInBOM_FALSE = 0
    swDmShowChildComponentsInBOM_TRUE = 1
    swDmShowChildComponentsInBOM_Promote = 2
    swDmShowChildComponentsInBOM_NotDefined = -1

class swDmTableCellHorzAlignType(_Enum):
    swDmTableCellHorzAlign_Left = 0
    swDmTableCellHorzAlign_Center = 1
    swDmTableCellHorzAlign_Right = 2
    swDmTableCellHorzAlign_General = 3
    swDmTableCellHorzAlign_None = 4
    swDmTableCellHorzAlign_Center_Center = 5
    swDmTableCellHorzAlign_Equal_Space = 6
    swDmTableCellHorzAlign_Unknown = -1

class swDmUnitSystem_e(_Enum):
    swDmUnitSystem_CGS = 1
    swDmUnitSystem_MKS = 2
    swDmUnitSystem_IPS = 3
    swDmUnitSystem_Custom = 4
    swDmUnitSystem_MMGS = 5

class swDmUnitsDecimalRounding_e(_Enum):
    swDmUnitsDecimalRounding_HalfAway = 0
    swDmUnitsDecimalRounding_HalfTowards = 1
    swDmUnitsDecimalRounding_HalfToEven = 2
    swDmUnitsDecimalRounding_Truncate = 3

class swDmUnitsEnergyUnit_e(_Enum):
    swDmUnitsEnergyUnit_Joules = 1
    swDmUnitsEnergyUnit_Ergs = 2
    swDmUnitsEnergyUnit_BTUs = 3
    swDmUnitsEnergyUnit_KilowattHours = 4

class swDmUnitsForce_e(_Enum):
    swDmUnitsForce_Dynes = 1
    swDmUnitsForce_Millinewtons = 2
    swDmUnitsForce_Newtons = 3
    swDmUnitsForce_Kilonewtons = 4
    swDmUnitsForce_Meganewtons = 5
    swDmUnitsForce_PoundForce = 6
    swDmUnitsForce_KgForce = 7
    swDmUnitsForce_OunceForce = 8

class swDmUnitsMassPropMass_e(_Enum):
    swDmUnitsMassPropMass_Milligrams = 1
    swDmUnitsMassPropMass_Grams = 2
    swDmUnitsMassPropMass_Kilograms = 3
    swDmUnitsMassPropMass_Pounds = 4

class swDmUnitsMassPropVolume_e(_Enum):
    swDmUnitsMassPropVolume_AngstromsCubed = 0
    swDmUnitsMassPropVolume_NanometersCubed = 1
    swDmUnitsMassPropVolume_MicronsCubed = 2
    swDmUnitsMassPropVolume_MillimetersCubed = 3
    swDmUnitsMassPropVolume_CentimetersCubed = 4
    swDmUnitsMassPropVolume_MetersCubed = 5
    swDmUnitsMassPropVolume_MicroInchesCubed = 6
    swDmUnitsMassPropVolume_MilsCubed = 7
    swDmUnitsMassPropVolume_InchesCubed = 8
    swDmUnitsMassPropVolume_FeetCubed = 9
    swDmUnitsMassPropVolume_Microliters = 10
    swDmUnitsMassPropVolume_Milliliters = 11
    swDmUnitsMassPropVolume_Centiliters = 12
    swDmUnitsMassPropVolume_Deciliters = 13
    swDmUnitsMassPropVolume_Liters = 14
    swDmUnitsMassPropVolume_Hectoliters = 15
    swDmUnitsMassPropVolume_USFluidOunces = 16
    swDmUnitsMassPropVolume_USPints = 17
    swDmUnitsMassPropVolume_USGallons = 18
    swDmUnitsMassPropVolume_IMPGallons = 19
    swDmUnitsMassPropVolume_IMPCubicYards = 20

class swDmUnitsPowerUnit_e(_Enum):
    swDmUnitsPowerUnit_Watts = 1
    swDmUnitsPowerUnit_Horsepower = 2
    swDmUnitsPowerUnit_Kilowatts = 3

class swDmUnitsTimeUnit_e(_Enum):
    swDmUnitsTimeUnit_Seconds = 1
    swDmUnitsTimeUnit_Milliseconds = 2
    swDmUnitsTimeUnit_Minutes = 3
    swDmUnitsTimeUnit_Hours = 4
    swDmUnitsTimeUnit_Microseconds = 5
    swDmUnitsTimeUnit_Nanoseconds = 6

class swSheetFormatPathResult(_Enum):
    swSheetFormatPath_FALSE = 0
    swSheetFormatPath_TRUE = 1
    swSheetFormatPath_NotDefined = -1

class swSheetPropertiesResult(_Enum):
    swSheetProperties_FALSE = 0
    swSheetProperties_TRUE = 1
    swSheetProperties_NotDefined = -1
