"""Motion studies API constants (SolidWorks.Interop.swmotionstudy 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swMotionIntegratorType_e(_Enum):
    swMotionIntegrator_GSTIFF = 1
    swMotionIntegrator_WSTIFF = 2
    swMotionIntegrator_SI2_GSTIFF = 3

class swMotionStudyNotify_e(_Enum):
    swMotionStudyMotorTimeStepChangeNotify = 1
    swMotionStudyForceTimeStepChangeNotify = 2
    swMotionStudyPartCollideNotify = 3
    swMotionStudyMotorOutputTimeStepChangeNotify = 4
    swMotionStudyStartCalculateNotify = 5
    swMotionStudyStopCalculateNotify = 6
    swMotionStudyForceOutputTimeStepChangeNotify = 7
    swMotionStudySpecialEventNotify = 8
    swMotionStudyOutputTimeStepChangeNotify = 9

class swMotionStudyType_e(_Enum):
    swMotionStudyTypeAssembly = 1
    swMotionStudyTypePhysicalSimulation = 2
    swMotionStudyTypeCosmosMotion = 4
    swMotionStudyTypeLegacyCosmosMotion = 8
    swMotionStudyTypeNewCosmosMotion = 16

class swSaveAVIImageSize_e(_Enum):
    swImage_Custom = 0
    swImage_Screen = 1
    swImage_160x120 = 2
    swImage_320x200 = 3
    swImage_320x240 = 4
    swImage_512x384 = 5
    swImage_640x480 = 6
    swImage_800x600 = 7

class swSpecialMotionEventType_e(_Enum):
    swSpecialMotionEventType_Contact = 1
