"""Routing API constants (SolidWorks.Interop.SWRoutingLib 28.1.0.74).

Auto-generated by tools/gen_interop.py - do not edit.
"""
from swpy.swconst import _Enum


class swAdvancedRouteSelectionOutput_e(_Enum):
    swBoth = 0
    swSelectOnly = 1
    swDataOnly = 2

class swAutoRouteAutoTangencyMode_e(_Enum):
    swAutoTangencyMode_OFF = 0
    swAutoTangencyMode_ON = 1

class swAutoRouteConversionMode_e(_Enum):
    swFlexibleAutoRouteMode = 1
    swOrthogonalAutoRouteMode = 2

class swAutoRouteErrorType_e(_Enum):
    swAutoRouteSuccess = 0
    swAutoRouteEntityTypeAndEntityIdMismatch = 1
    swAutoRouteFailed = 2

class swAutoRouteSketchEntitiesTypes_e(_Enum):
    swAutoRouteSketchEntitiesType_Point = 0
    swAutoRouteSketchEntitiesType_Line = 1
    swAutoRouteSketchEntitiesType_Arc = 2
    swAutoRouteSketchEntitiesType_Spline = 3

class swCPointConfig_e(_Enum):
    swCPointConfig_AddAllCPoint = 1
    swCPointConfig_DoNotAddCPoint = 2
    swCPointConfig_SelectCPoints = 3

class swComponentCrossSectionType_e(_Enum):
    swRectangularCrossSection = 1000
    swCircularCrossSection = 1010
    swNotHVAC = 1020

class swComponentRouteType_e(_Enum):
    swFabricatedPipe = 1
    swTube = 2
    swElectrical = 3
    swMixedRouteType = 4
    swUnknownType = 5
    swUserDefinedType = 6

class swElectricalRouteSubType_e(_Enum):
    swRouteSubType_Harness = 0
    swRouteSubType_CableWire = 1
    swRouteSubType_Conduit = 2
    swRouteSubType_Ribbon = 3

class swElectricalStreamType_e(_Enum):
    swAllStreams = 0
    swFromToListStream = 2
    swSegmentDataStream = 3
    swWireListStream = 4

class swExportTubeDataReportType_e(_Enum):
    swExportTubeDataReportType_Tangent = 1
    swExportTubeDataReportType_XYZ = 2

class swFlattenRouteErrorType_e(_Enum):
    swNeedsToSaveVirtualComponentError = 1
    swProblemInRouteAssemblyError = 2
    swDuplicateComponentError = 3
    swRouteAssemblyNotSelected = 4
    swFlattenRouteNoError = 5

class swForceUpdateElectricalDataError_e(_Enum):
    swForceUpdateElectricalData_Success = 0
    swForceUpdateElectricalData_IncorrectStreamInput = 1
    swForceUpdateElectricalData_IsNotARouteAssembly = 2
    swForceUpdateElectricalData_BadStreamData = 3
    swForceUpdateElectricalData_RouteInEditMode = 4

class swMinimumBendRadiusChecks_e(_Enum):
    swMinimumBendRadiusChecks_None = 0
    swMinimumBendRadiusChecks_WiresOnly = 1
    swMinimumBendRadiusChecks_CablesAndWires = 2

class swPointToPointAutoRouteConversionMode_e(_Enum):
    swFlexibleMode = 1
    swOrthogonalMode = 2

class swPointToPointAutoRouteErrorType_e(_Enum):
    swRouteTypeAndConversionModeMismatch = 1
    swCouldNotCreateRoute = 2
    swNoRouteFound = 3
    swPointToPointAutoRouteNoError = 4

class swRouteComponentTypeID_e(_Enum):
    swRouteCompType_Unknown = 0
    swRouteCompType_Pipe = 1
    swRouteCompType_EndConnector = 2
    swRouteCompType_Flange = 3
    swRouteCompType_OLet = 4
    swRouteCompType_Tee = 5
    swRouteCompType_ReducingTee = 6
    swRouteCompType_Elbow = 7
    swRouteCompType_Reducer = 8
    swRouteCompType_EccentricReducer = 9
    swRouteCompType_Union = 10
    swRouteCompType_Adapter = 11
    swRouteCompType_Cross = 12
    swRouteCompType_ReducingCross = 13
    swRouteCompType_Clip = 14
    swRouteCompType_Support = 15
    swRouteCompType_Equipment = 16
    swRouteCompType_TeeAdapter = 17
    swRouteCompType_HybridComponents = 18
    swRouteCompType_FittingOther = 19
    swRouteCompType_Hanger = 20
    swRouteCompType_ConduitAdapter = 21
    swRouteCompType_Gasket = 22
    swRouteCompType_Valve = 23
    swRouteCompType_RibbonCable = 24
    swRouteCompType_Tube = 25
    swRouteCompType_Conduit = 26
    swRouteCompType_Splice = 27
    swRouteCompType_ConduitElbow = 28
    swRouteCompType_AssemblyFittings = 29
    swRouteCompType_CableTray = 30
    swRouteCompType_DuctingTrunking = 31
    swRouteCompType_FlexCableConnector = 32
    swRouteCompType_Nipple = 33

class swRouteType_e(_Enum):
    swRouteType_Electrical = 2

class swRoutingExportDataError_e(_Enum):
    swRoutingExportDataError_Success = 0
    swRoutingExportDataError_UnknownError = 1
    swRoutingExportDataError_IncorrectFilePath = 2
    swRoutingExportDataError_AssemblyTypeMismatch = 3
    swRoutingExportDataError_WrongUnit = 4
    swRoutingExportDataError_WrongType = 5

class swRoutingExportPipeDataError_e(_Enum):
    swRoutingExportPipeDataError_Success = 0
    swRoutingExportPipeDataError_UnknownError = 1
    swRoutingExportPipeDataError_IncorrectFilePath = 2
    swRoutingExportPipeDataError_AssemblyTypeMismatch = 3
    swRoutingExportPipeDataError_WrongUnit = 4

class swSetRoutePathForWireErrorType_e(_Enum):
    swSetRoutePathSuccess = 0
    swSetRoutePathTooManyConnectorsSelected = 1
    swSetRoutePathFailed = 2

class swUserPreferenceRoutingDouble_e(_Enum):
    swSlackPercentage = 1
    swTextSizeForConnectionAndRoutePoints = 2

class swUserPreferenceRoutingFileLocations_e(_Enum):
    swRoutingLibraryPath = 1
    swFileLocationsRoutingAssemblyTemplate = 2
    swFileLocationsRoutingStandardTubes = 3
    swFileLocationsRoutingPipeTubeCoveringLibrary = 4
    swFileLocationsRoutingCableLibrary = 5
    swFileLocationsRoutingComponentLibrary = 6
    swFileLocationsRoutingStandardCable = 7
    swFileLocationsRoutingCoveringLibrary = 8
    swFileLocationsRoutingTagSchemes = 9
    swFileLocationsRoutingInterconnectsLibrary = 10

class swUserPreferenceRoutingInteger_e(_Enum):
    swComponentRotationIncrementDegrees = 1
    swEnableMinimumBendRadiusChecks = 2

class swUserPreferenceRoutingToggle_e(_Enum):
    swAutomaticallyCreateSketchFillets = 1
    swSaveRouteAssemblyExternally = 2
    swSaveRoutePartsExternally = 3
    swUseAutomaticNamingForRouteParts = 4
    swCreateCustomFittings = 5
    swCreatePipesOnOpenLineSegments = 6
    swAutomaticallyRouteOnDropOfFlangeConnectors = 7
    swAutomaticallyRouteOnDropOfClips = 8
    swAutomaticallyAddDimensionToRouteStubs = 9
    swEnableRouteErrorChecking = 10
    swDisplayErrorBalloons = 11
    swIncludeCoveringsInBOM = 12
    swAlwaysUseDefaultDocumentTemplate = 13
    swUseTriadToPosAndOrientComp = 14
    swUseAutoNamingForRouteParts = 15
    swUseCenterlineDim = 16
    swAutomaticallyZoomToFitRouteComponents = 17
    swUseConfigureComponentsToSelectConfigurations = 18
    swCreateRoutePartForSegmentsHavingBendRadiusLessThanMinimum = 19

class swWireRouteError_e(_Enum):
    swWireRouteError_WireNotRouted = 1
    swWireRouteError_WireSegmentsBranching = 2
    swWireRouteError_WireSegmentsDisjoint = 3
    swWireRouteError_WireMissingFromToComponent = 4
    swWireRouteError_WireMismatchedFromComponent = 5
    swWireRouteError_WireMismatchedToComponent = 6
    swWireRouteError_WireMismatchedFromPin = 7
    swWireRouteError_WireMismatchedToPin = 8
    swWireRouteError_WirePathViolatesBendRadius = 9
