"""Generate interop glue from the SOLIDWORKS interop assemblies.

Outputs:
  src/SwPy.AddIn/Scripting/Cast.g.cs  - one typed cast per sldworks interface
  python/swpy/swconst.py              - all swconst enums as plain Python classes

Why: pythonnet resolves `SolidWorks.Interop.*` imports to whichever loaded assembly defines the
type first, and add-ins like McMaster-Carr embed trimmed copies. A C# method whose declared return
type is the real interface makes pythonnet wrap the object with the real type.

Run with the project venv (pythonnet):  .venv\\Scripts\\python tools\\gen_interop.py
"""
import os
import sys

from pythonnet import load

load("netfx")
import clr  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REDIST = os.environ.get("SWPY_REDIST", r"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist")

sldworks = clr.AddReference(os.path.join(REDIST, "SolidWorks.Interop.sldworks.dll"))
swconst = clr.AddReference(os.path.join(REDIST, "SolidWorks.Interop.swconst.dll"))


def gen_casts():
    names = sorted(t.Name for t in sldworks.GetExportedTypes()
                   if t.IsInterface and t.Namespace == "SolidWorks.Interop.sldworks")
    ver = sldworks.GetName().Version
    lines = [
        "// <auto-generated> by tools/gen_interop.py from SolidWorks.Interop.sldworks "
        f"{ver}. Do not edit. </auto-generated>",
        "using SW = SolidWorks.Interop.sldworks;",
        "",
        "namespace SwPy.Scripting",
        "{",
        "    /// <summary>Typed casts: the declared return type makes pythonnet wrap with the real interface.</summary>",
        "    public static class Cast",
        "    {",
    ]
    lines += [f"        public static SW.{n} {n}(object o) => (SW.{n})o;" for n in names]
    lines += ["    }", "}", ""]
    path = os.path.join(ROOT, "src", "SwPy.AddIn", "Scripting", "Cast.g.cs")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return path, len(names)


def gen_swconst():
    import System
    enums = sorted((t for t in swconst.GetExportedTypes() if t.IsEnum), key=lambda t: t.Name)
    ver = swconst.GetName().Version
    out = [
        f'"""SOLIDWORKS API constants (SolidWorks.Interop.swconst {ver}).',
        "",
        "Auto-generated by tools/gen_interop.py - do not edit.",
        "Plain ints: the SOLIDWORKS API takes enum arguments as int.",
        '"""',
        "",
        "",
        "class _Enum:",
        '    """Namespace of int constants with reverse lookup: swDocumentTypes_e.name(1)."""',
        "",
        "    @classmethod",
        "    def name(cls, value):",
        "        for k, v in vars(cls).items():",
        "            if not k.startswith('_') and v == value:",
        "                return k",
        "        return None",
        "",
        "    @classmethod",
        "    def items(cls):",
        "        return {k: v for k, v in vars(cls).items() if not k.startswith('_') and isinstance(v, int)}",
        "",
    ]
    for t in enums:
        out += ["", f"class {t.Name}(_Enum):"]
        names = list(System.Enum.GetNames(t))
        if not names:
            out.append("    pass")
            continue
        under = System.Enum.GetUnderlyingType(t)
        for n in names:
            value = System.Convert.ChangeType(System.Enum.Parse(t, n), under)
            out.append(f"    {n} = {int(value)}")
    path = os.path.join(ROOT, "python", "swpy", "swconst.py")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return path, len(enums)


if __name__ == "__main__":
    for fn in (gen_casts, gen_swconst):
        p, n = fn()
        print(f"{n:5d} items -> {os.path.relpath(p, ROOT)}")
    sys.exit(0)
