"""Generate interop glue from the SOLIDWORKS interop assemblies.

Outputs:
  src/SwPy.AddIn/Scripting/Cast.g.cs  - one typed cast per sldworks interface
  python/swpy/swconst.py              - all swconst enums as plain Python classes

Why: pythonnet resolves `SolidWorks.Interop.*` imports to whichever loaded assembly defines the
type first, and add-ins like McMaster-Carr embed trimmed copies. A C# method whose declared return
type is the real interface makes pythonnet wrap the object with the real type.

Run with the project venv (pythonnet):  .venv\\Scripts\\python tools\\gen_interop.py
"""
import os
import sys

from pythonnet import load

load("netfx")
import clr  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REDIST = os.environ.get("SWPY_REDIST", r"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist")

sldworks = clr.AddReference(os.path.join(REDIST, "SolidWorks.Interop.sldworks.dll"))
swconst = clr.AddReference(os.path.join(REDIST, "SolidWorks.Interop.swconst.dll"))


def gen_casts():
    names = sorted(t.Name for t in sldworks.GetExportedTypes()
                   if t.IsInterface and t.Namespace == "SolidWorks.Interop.sldworks")
    ver = sldworks.GetName().Version
    lines = [
        "// <auto-generated> by tools/gen_interop.py from SolidWorks.Interop.sldworks "
        f"{ver}. Do not edit. </auto-generated>",
        "using SW = SolidWorks.Interop.sldworks;",
        "",
        "namespace SwPy.Scripting",
        "{",
        "    /// <summary>Typed casts: the declared return type makes pythonnet wrap with the real interface.</summary>",
        "    public static class Cast",
        "    {",
    ]
    lines += [f"        public static SW.{n} {n}(object o) => (SW.{n})o;" for n in names]
    lines += ["    }", "}", ""]
    path = os.path.join(ROOT, "src", "SwPy.AddIn", "Scripting", "Cast.g.cs")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return path, len(names)


def gen_swconst():
    import System
    enums = sorted((t for t in swconst.GetExportedTypes() if t.IsEnum), key=lambda t: t.Name)
    ver = swconst.GetName().Version
    out = [
        f'"""SOLIDWORKS API constants (SolidWorks.Interop.swconst {ver}).',
        "",
        "Auto-generated by tools/gen_interop.py - do not edit.",
        "Plain ints: the SOLIDWORKS API takes enum arguments as int.",
        '"""',
        "",
        "",
        "class _Enum:",
        '    """Namespace of int constants with reverse lookup: swDocumentTypes_e.name(1)."""',
        "",
        "    @classmethod",
        "    def name(cls, value):",
        "        for k, v in vars(cls).items():",
        "            if not k.startswith('_') and v == value:",
        "                return k",
        "        return None",
        "",
        "    @classmethod",
        "    def items(cls):",
        "        return {k: v for k, v in vars(cls).items() if not k.startswith('_') and isinstance(v, int)}",
        "",
    ]
    for t in enums:
        out += ["", f"class {t.Name}(_Enum):"]
        names = list(System.Enum.GetNames(t))
        if not names:
            out.append("    pass")
            continue
        under = System.Enum.GetUnderlyingType(t)
        for n in names:
            value = System.Convert.ChangeType(System.Enum.Parse(t, n), under)
            out.append(f"    {n} = {int(value)}")
    path = os.path.join(ROOT, "python", "swpy", "swconst.py")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return path, len(enums)


# ---------------------------------------------------------------- other API libraries

SWDIR = os.path.dirname(os.path.dirname(REDIST))

# python name, file (relative to the SOLIDWORKS folder), title. The python name is the interop namespace's
# last segment, as used in VBA/C# (`SolidWorks.Interop.cosworks` -> `cosworks`).
LIBRARIES = [
    ("cosworks", r"api\redist\SolidWorks.Interop.cosworks.dll", "SOLIDWORKS Simulation"),
    ("swmotionstudy", r"api\redist\SolidWorks.Interop.swmotionstudy.dll", "Motion studies"),
    ("swdimxpert", r"api\redist\SolidWorks.Interop.swdimxpert.dll", "DimXpert"),
    ("SWRoutingLib", r"SolidWorks.Interop.SWRoutingLib.dll", "Routing"),
    ("sldcostingapi", r"api\redist\SolidWorks.Interop.sldcostingapi.dll", "Costing"),
    ("dsgnchk", r"api\redist\SolidWorks.Interop.dsgnchk.dll", "Design Checker"),
    ("fworks", r"api\redist\SolidWorks.Interop.fworks.dll", "FeatureWorks"),
    ("gtswutilities", r"api\redist\SolidWorks.Interop.gtswutilities.dll", "Utilities"),
    ("sldtoolboxconfigureaddin", r"api\redist\SolidWorks.Interop.sldtoolboxconfigureaddin.dll", "Toolbox"),
    ("sustainability", r"api\redist\SolidWorks.Interop.sustainability.dll", "Sustainability"),
    ("sw3dprinter", r"api\redist\SolidWorks.Interop.sw3dprinter.dll", "3D printing"),
    ("swbrowser", r"api\redist\SolidWorks.Interop.swbrowser.dll", "Design Library browser"),
    ("swcommands", r"api\redist\SolidWorks.Interop.swcommands.dll", "Command IDs for ISldWorks.RunCommand"),
    ("swdocumentmgr", r"api\redist\SolidWorks.Interop.swdocumentmgr.dll", "Document Manager (needs a licence key)"),
    ("EdmLib", r"Interop.SWEdmLib.dll", "SOLIDWORKS PDM Professional"),
    ("pdmworks", r"api\redist\PDMWorks.Interop.pdmworks.dll", "Workgroup PDM (legacy)"),
]


def _is_event(t):
    """COM event plumbing (DFooEvents, DFooEvents_Event): not useful as casts, unsafe to probe."""
    return (t.Name.endswith("_Event") or t.Name.startswith("_")
            or (t.Name.startswith("D") and t.Name.endswith("Events")))


def _load_library(rel):
    path = os.path.join(SWDIR, rel)
    return clr.AddReference(path) if os.path.exists(path) else None


def _write_enums(asm, path, title):
    import keyword
    import System
    # skip MIDL's anonymous duplicates (__MIDL___MIDL_itf_...) - the named enums carry the same values
    enums = sorted((t for t in asm.GetExportedTypes() if t.IsEnum and not t.Name.startswith("_")), key=lambda t: t.Name)
    out = [f'"""{title} API constants ({asm.GetName().Name} {asm.GetName().Version}).', "",
           "Auto-generated by tools/gen_interop.py - do not edit.", '"""', "from swpy.swconst import _Enum", ""]
    for t in enums:
        out += ["", f"class {t.Name}(_Enum):"]
        names = list(System.Enum.GetNames(t))
        if not names:
            out.append("    pass")
            continue
        under = System.Enum.GetUnderlyingType(t)
        for n in names:
            value = System.Convert.ChangeType(System.Enum.Parse(t, n), under)
            out.append(f"    {n + '_' if keyword.iskeyword(n) else n} = {int(value)}")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return len(enums)


def gen_libraries():
    """Typed casts (C#) + constants (Python) + metadata for every other API library that is installed."""
    cs = ["// <auto-generated> by tools/gen_interop.py. Do not edit. </auto-generated>",
          "// One class per library: pythonnet only loads a library's interop assembly when its class is used.",
          "namespace SwPy.Scripting.Libraries", "{"]
    meta, libs_dir = [], os.path.join(ROOT, "python", "swpy", "libs")
    os.makedirs(libs_dir, exist_ok=True)
    for name, rel, title in LIBRARIES:
        asm = _load_library(rel)
        if asm is None:
            print(f"      skipped {name}: {rel} not found")
            continue
        types = list(asm.GetExportedTypes())
        namespace = types[0].Namespace
        ifaces = sorted(t.Name for t in types if t.IsInterface and t.Namespace == namespace and not _is_event(t))
        cls = f"Cast_{name}"
        cs += [f"    /// <summary>{title}: typed casts for {namespace}.</summary>",
               f"    public static class {cls}", "    {"]
        cs += [f"        public static global::{namespace}.{n} {n}(object o) => (global::{namespace}.{n})o;"
               for n in ifaces]
        cs += ["    }", ""]
        n_enums = _write_enums(asm, os.path.join(libs_dir, name + ".py"), title)
        meta.append(f"    {name!r}: {{'title': {title!r}, 'namespace': {namespace!r}, "
                    f"'assembly': {asm.GetName().Name!r}, 'file': {rel!r}, 'casts': {cls!r}, "
                    f"'interfaces': {len(ifaces)}, 'enums': {n_enums}}},")
    cs += ["}", ""]
    with open(os.path.join(ROOT, "src", "SwPy.AddIn", "Scripting", "Libraries.g.cs"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write("\n".join(cs))
    with open(os.path.join(libs_dir, "__init__.py"), "w", encoding="utf-8", newline="\n") as f:
        f.write('"""SOLIDWORKS API libraries besides sldworks: metadata for swpy._interop.\n\n'
                'Auto-generated by tools/gen_interop.py - do not edit.\n"""\n'
                "LIBRARIES = {\n" + "\n".join(meta) + "\n}\n")
    return libs_dir, len(meta)


if __name__ == "__main__":
    for fn in (gen_casts, gen_swconst, gen_libraries):
        p, n = fn()
        print(f"{n:5d} items -> {os.path.relpath(p, ROOT)}")
    sys.exit(0)
